/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db;


import com.agri.mis.db.tables.Address;
import com.agri.mis.db.tables.AuthorizationConsent;
import com.agri.mis.db.tables.BatchBase;
import com.agri.mis.db.tables.BatchCycle;
import com.agri.mis.db.tables.BatchCycleExecute;
import com.agri.mis.db.tables.BatchCycleExpense;
import com.agri.mis.db.tables.BatchCycleExpenseItem;
import com.agri.mis.db.tables.BatchProduct;
import com.agri.mis.db.tables.BatchRisk;
import com.agri.mis.db.tables.BatchTeam;
import com.agri.mis.db.tables.Category;
import com.agri.mis.db.tables.CheckTemp;
import com.agri.mis.db.tables.CheckTempItem;
import com.agri.mis.db.tables.CheckTrace;
import com.agri.mis.db.tables.CmsBlog;
import com.agri.mis.db.tables.CmsCategory;
import com.agri.mis.db.tables.CmsResource;
import com.agri.mis.db.tables.CmsTag;
import com.agri.mis.db.tables.Corp;
import com.agri.mis.db.tables.CorpDepart;
import com.agri.mis.db.tables.CorpManager;
import com.agri.mis.db.tables.CorpManagerDepart;
import com.agri.mis.db.tables.CorpManagerRole;
import com.agri.mis.db.tables.CorpPark;
import com.agri.mis.db.tables.CorpParkBase;
import com.agri.mis.db.tables.CorpRole;
import com.agri.mis.db.tables.CorpRoleMenu;
import com.agri.mis.db.tables.Customer;
import com.agri.mis.db.tables.CustomerLink;
import com.agri.mis.db.tables.CustomerTrace;
import com.agri.mis.db.tables.DocResource;
import com.agri.mis.db.tables.MarkCategory;
import com.agri.mis.db.tables.MarkMarket;
import com.agri.mis.db.tables.MarkProduct;
import com.agri.mis.db.tables.MarkProductBatch;
import com.agri.mis.db.tables.MarkProductCycle;
import com.agri.mis.db.tables.MarkProductCycleExpense;
import com.agri.mis.db.tables.MarkProductMarket;
import com.agri.mis.db.tables.MarkProductRisk;
import com.agri.mis.db.tables.MisAccountBill;
import com.agri.mis.db.tables.MisAccountTitle;
import com.agri.mis.db.tables.MisBankAccount;
import com.agri.mis.db.tables.MisContract;
import com.agri.mis.db.tables.MisProductionOrder;
import com.agri.mis.db.tables.MisProductionOrderItem;
import com.agri.mis.db.tables.MisPurchaseOrder;
import com.agri.mis.db.tables.MisPurchaseOrderItem;
import com.agri.mis.db.tables.MisSaleOrder;
import com.agri.mis.db.tables.MisSaleOrderItem;
import com.agri.mis.db.tables.MisStock;
import com.agri.mis.db.tables.MisStockItem;
import com.agri.mis.db.tables.MisStockPlace;
import com.agri.mis.db.tables.MisStockPlaceItem;
import com.agri.mis.db.tables.MisStockPlaceItemSub;
import com.agri.mis.db.tables.MisStore;
import com.agri.mis.db.tables.MisStoreItem;
import com.agri.mis.db.tables.Oauth2Authorization;
import com.agri.mis.db.tables.Oauth2RegisteredClient;
import com.agri.mis.db.tables.Product;
import com.agri.mis.db.tables.SysConst;
import com.agri.mis.db.tables.SysConstItem;
import com.agri.mis.db.tables.SysMenu;
import com.agri.mis.db.tables.SysMenuAction;
import com.agri.mis.db.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.authorization_consent</code>.
     */
    public final AuthorizationConsent AUTHORIZATION_CONSENT = AuthorizationConsent.AUTHORIZATION_CONSENT;

    /**
     * The table <code>public.batch_base</code>.
     */
    public final BatchBase BATCH_BASE = BatchBase.BATCH_BASE;

    /**
     * The table <code>public.batch_cycle</code>.
     */
    public final BatchCycle BATCH_CYCLE = BatchCycle.BATCH_CYCLE;

    /**
     * The table <code>public.batch_cycle_execute</code>.
     */
    public final BatchCycleExecute BATCH_CYCLE_EXECUTE = BatchCycleExecute.BATCH_CYCLE_EXECUTE;

    /**
     * The table <code>public.batch_cycle_expense</code>.
     */
    public final BatchCycleExpense BATCH_CYCLE_EXPENSE = BatchCycleExpense.BATCH_CYCLE_EXPENSE;

    /**
     * The table <code>public.batch_cycle_expense_item</code>.
     */
    public final BatchCycleExpenseItem BATCH_CYCLE_EXPENSE_ITEM = BatchCycleExpenseItem.BATCH_CYCLE_EXPENSE_ITEM;

    /**
     * The table <code>public.batch_product</code>.
     */
    public final BatchProduct BATCH_PRODUCT = BatchProduct.BATCH_PRODUCT;

    /**
     * The table <code>public.batch_risk</code>.
     */
    public final BatchRisk BATCH_RISK = BatchRisk.BATCH_RISK;

    /**
     * The table <code>public.batch_team</code>.
     */
    public final BatchTeam BATCH_TEAM = BatchTeam.BATCH_TEAM;

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.check_temp</code>.
     */
    public final CheckTemp CHECK_TEMP = CheckTemp.CHECK_TEMP;

    /**
     * The table <code>public.check_temp_item</code>.
     */
    public final CheckTempItem CHECK_TEMP_ITEM = CheckTempItem.CHECK_TEMP_ITEM;

    /**
     * The table <code>public.check_trace</code>.
     */
    public final CheckTrace CHECK_TRACE = CheckTrace.CHECK_TRACE;

    /**
     * The table <code>public.cms_blog</code>.
     */
    public final CmsBlog CMS_BLOG = CmsBlog.CMS_BLOG;

    /**
     * The table <code>public.cms_category</code>.
     */
    public final CmsCategory CMS_CATEGORY = CmsCategory.CMS_CATEGORY;

    /**
     * The table <code>public.cms_resource</code>.
     */
    public final CmsResource CMS_RESOURCE = CmsResource.CMS_RESOURCE;

    /**
     * The table <code>public.cms_tag</code>.
     */
    public final CmsTag CMS_TAG = CmsTag.CMS_TAG;

    /**
     * The table <code>public.corp</code>.
     */
    public final Corp CORP = Corp.CORP;

    /**
     * The table <code>public.corp_depart</code>.
     */
    public final CorpDepart CORP_DEPART = CorpDepart.CORP_DEPART;

    /**
     * The table <code>public.corp_manager</code>.
     */
    public final CorpManager CORP_MANAGER = CorpManager.CORP_MANAGER;

    /**
     * The table <code>public.corp_manager_depart</code>.
     */
    public final CorpManagerDepart CORP_MANAGER_DEPART = CorpManagerDepart.CORP_MANAGER_DEPART;

    /**
     * The table <code>public.corp_manager_role</code>.
     */
    public final CorpManagerRole CORP_MANAGER_ROLE = CorpManagerRole.CORP_MANAGER_ROLE;

    /**
     * The table <code>public.corp_park</code>.
     */
    public final CorpPark CORP_PARK = CorpPark.CORP_PARK;

    /**
     * The table <code>public.corp_park_base</code>.
     */
    public final CorpParkBase CORP_PARK_BASE = CorpParkBase.CORP_PARK_BASE;

    /**
     * The table <code>public.corp_role</code>.
     */
    public final CorpRole CORP_ROLE = CorpRole.CORP_ROLE;

    /**
     * The table <code>public.corp_role_menu</code>.
     */
    public final CorpRoleMenu CORP_ROLE_MENU = CorpRoleMenu.CORP_ROLE_MENU;

    /**
     * The table <code>public.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.customer_link</code>.
     */
    public final CustomerLink CUSTOMER_LINK = CustomerLink.CUSTOMER_LINK;

    /**
     * The table <code>public.customer_trace</code>.
     */
    public final CustomerTrace CUSTOMER_TRACE = CustomerTrace.CUSTOMER_TRACE;

    /**
     * The table <code>public.doc_resource</code>.
     */
    public final DocResource DOC_RESOURCE = DocResource.DOC_RESOURCE;

    /**
     * The table <code>public.mark_category</code>.
     */
    public final MarkCategory MARK_CATEGORY = MarkCategory.MARK_CATEGORY;

    /**
     * The table <code>public.mark_market</code>.
     */
    public final MarkMarket MARK_MARKET = MarkMarket.MARK_MARKET;

    /**
     * The table <code>public.mark_product</code>.
     */
    public final MarkProduct MARK_PRODUCT = MarkProduct.MARK_PRODUCT;

    /**
     * The table <code>public.mark_product_batch</code>.
     */
    public final MarkProductBatch MARK_PRODUCT_BATCH = MarkProductBatch.MARK_PRODUCT_BATCH;

    /**
     * The table <code>public.mark_product_cycle</code>.
     */
    public final MarkProductCycle MARK_PRODUCT_CYCLE = MarkProductCycle.MARK_PRODUCT_CYCLE;

    /**
     * The table <code>public.mark_product_cycle_expense</code>.
     */
    public final MarkProductCycleExpense MARK_PRODUCT_CYCLE_EXPENSE = MarkProductCycleExpense.MARK_PRODUCT_CYCLE_EXPENSE;

    /**
     * The table <code>public.mark_product_market</code>.
     */
    public final MarkProductMarket MARK_PRODUCT_MARKET = MarkProductMarket.MARK_PRODUCT_MARKET;

    /**
     * The table <code>public.mark_product_risk</code>.
     */
    public final MarkProductRisk MARK_PRODUCT_RISK = MarkProductRisk.MARK_PRODUCT_RISK;

    /**
     * The table <code>public.mis_account_bill</code>.
     */
    public final MisAccountBill MIS_ACCOUNT_BILL = MisAccountBill.MIS_ACCOUNT_BILL;

    /**
     * The table <code>public.mis_account_title</code>.
     */
    public final MisAccountTitle MIS_ACCOUNT_TITLE = MisAccountTitle.MIS_ACCOUNT_TITLE;

    /**
     * The table <code>public.mis_bank_account</code>.
     */
    public final MisBankAccount MIS_BANK_ACCOUNT = MisBankAccount.MIS_BANK_ACCOUNT;

    /**
     * The table <code>public.mis_contract</code>.
     */
    public final MisContract MIS_CONTRACT = MisContract.MIS_CONTRACT;

    /**
     * The table <code>public.mis_production_order</code>.
     */
    public final MisProductionOrder MIS_PRODUCTION_ORDER = MisProductionOrder.MIS_PRODUCTION_ORDER;

    /**
     * The table <code>public.mis_production_order_item</code>.
     */
    public final MisProductionOrderItem MIS_PRODUCTION_ORDER_ITEM = MisProductionOrderItem.MIS_PRODUCTION_ORDER_ITEM;

    /**
     * The table <code>public.mis_purchase_order</code>.
     */
    public final MisPurchaseOrder MIS_PURCHASE_ORDER = MisPurchaseOrder.MIS_PURCHASE_ORDER;

    /**
     * The table <code>public.mis_purchase_order_item</code>.
     */
    public final MisPurchaseOrderItem MIS_PURCHASE_ORDER_ITEM = MisPurchaseOrderItem.MIS_PURCHASE_ORDER_ITEM;

    /**
     * The table <code>public.mis_sale_order</code>.
     */
    public final MisSaleOrder MIS_SALE_ORDER = MisSaleOrder.MIS_SALE_ORDER;

    /**
     * The table <code>public.mis_sale_order_item</code>.
     */
    public final MisSaleOrderItem MIS_SALE_ORDER_ITEM = MisSaleOrderItem.MIS_SALE_ORDER_ITEM;

    /**
     * The table <code>public.mis_stock</code>.
     */
    public final MisStock MIS_STOCK = MisStock.MIS_STOCK;

    /**
     * The table <code>public.mis_stock_item</code>.
     */
    public final MisStockItem MIS_STOCK_ITEM = MisStockItem.MIS_STOCK_ITEM;

    /**
     * The table <code>public.mis_stock_place</code>.
     */
    public final MisStockPlace MIS_STOCK_PLACE = MisStockPlace.MIS_STOCK_PLACE;

    /**
     * The table <code>public.mis_stock_place_item</code>.
     */
    public final MisStockPlaceItem MIS_STOCK_PLACE_ITEM = MisStockPlaceItem.MIS_STOCK_PLACE_ITEM;

    /**
     * The table <code>public.mis_stock_place_item_sub</code>.
     */
    public final MisStockPlaceItemSub MIS_STOCK_PLACE_ITEM_SUB = MisStockPlaceItemSub.MIS_STOCK_PLACE_ITEM_SUB;

    /**
     * The table <code>public.mis_store</code>.
     */
    public final MisStore MIS_STORE = MisStore.MIS_STORE;

    /**
     * The table <code>public.mis_store_item</code>.
     */
    public final MisStoreItem MIS_STORE_ITEM = MisStoreItem.MIS_STORE_ITEM;

    /**
     * The table <code>public.oauth2_authorization</code>.
     */
    public final Oauth2Authorization OAUTH2_AUTHORIZATION = Oauth2Authorization.OAUTH2_AUTHORIZATION;

    /**
     * The table <code>public.oauth2_registered_client</code>.
     */
    public final Oauth2RegisteredClient OAUTH2_REGISTERED_CLIENT = Oauth2RegisteredClient.OAUTH2_REGISTERED_CLIENT;

    /**
     * The table <code>public.product</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.sys_const</code>.
     */
    public final SysConst SYS_CONST = SysConst.SYS_CONST;

    /**
     * The table <code>public.sys_const_item</code>.
     */
    public final SysConstItem SYS_CONST_ITEM = SysConstItem.SYS_CONST_ITEM;

    /**
     * The table <code>public.sys_menu</code>.
     */
    public final SysMenu SYS_MENU = SysMenu.SYS_MENU;

    /**
     * The table <code>public.sys_menu_action</code>.
     */
    public final SysMenuAction SYS_MENU_ACTION = SysMenuAction.SYS_MENU_ACTION;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.ACCOUNT_PEND_ID_SEQ,
            Sequences.ACCOUNT_TITLE_ID_SEQ,
            Sequences.BATCH_CYCLE_EXPENSE_SEQ,
            Sequences.CHECK_PROCESS_ID_SEQ,
            Sequences.CMS_VIDEO_ID_SEQ,
            Sequences.CONTRACT_ID_SEQ,
            Sequences.CORP_MANAGE_ID_SEQ,
            Sequences.MARKET_ID_SEQ,
            Sequences.MK_CATEGORY_ID_SEQ,
            Sequences.MK_PRODUCT_ID_SEQ,
            Sequences.PARK_BASE_ID_SEQ,
            Sequences.PARK_ID_SEQ,
            Sequences.PRODUCT_BATCH_ID_SEQ,
            Sequences.PRODUCT_CYCLE_EXPENSE_ID_SEQ,
            Sequences.PRODUCT_CYCLE_ID_SEQ,
            Sequences.PRODUCT_MARKET_ID_SEQ,
            Sequences.PRODUCT_RISK_ID_SEQ,
            Sequences.PRODUCTION_ORDER_ID_SEQ,
            Sequences.PRODUCTION_ORDER_ITEM_ID_SEQ,
            Sequences.PURCHASE_ORDER_ID_SEQ,
            Sequences.PURCHASE_ORDER_ITEM_ID_SEQ,
            Sequences.SALE_ORDER_ID_SEQ,
            Sequences.SALE_ORDER_ITEM_ID_SEQ,
            Sequences.STOCK_ID_SEQ,
            Sequences.STOCK_ITEM_ID_SEQ,
            Sequences.STORE_ID_SEQ,
            Sequences.STORE_ITEM_ID_SEQ,
            Sequences.USER_DOCUMENT_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Address.ADDRESS,
            AuthorizationConsent.AUTHORIZATION_CONSENT,
            BatchBase.BATCH_BASE,
            BatchCycle.BATCH_CYCLE,
            BatchCycleExecute.BATCH_CYCLE_EXECUTE,
            BatchCycleExpense.BATCH_CYCLE_EXPENSE,
            BatchCycleExpenseItem.BATCH_CYCLE_EXPENSE_ITEM,
            BatchProduct.BATCH_PRODUCT,
            BatchRisk.BATCH_RISK,
            BatchTeam.BATCH_TEAM,
            Category.CATEGORY,
            CheckTemp.CHECK_TEMP,
            CheckTempItem.CHECK_TEMP_ITEM,
            CheckTrace.CHECK_TRACE,
            CmsBlog.CMS_BLOG,
            CmsCategory.CMS_CATEGORY,
            CmsResource.CMS_RESOURCE,
            CmsTag.CMS_TAG,
            Corp.CORP,
            CorpDepart.CORP_DEPART,
            CorpManager.CORP_MANAGER,
            CorpManagerDepart.CORP_MANAGER_DEPART,
            CorpManagerRole.CORP_MANAGER_ROLE,
            CorpPark.CORP_PARK,
            CorpParkBase.CORP_PARK_BASE,
            CorpRole.CORP_ROLE,
            CorpRoleMenu.CORP_ROLE_MENU,
            Customer.CUSTOMER,
            CustomerLink.CUSTOMER_LINK,
            CustomerTrace.CUSTOMER_TRACE,
            DocResource.DOC_RESOURCE,
            MarkCategory.MARK_CATEGORY,
            MarkMarket.MARK_MARKET,
            MarkProduct.MARK_PRODUCT,
            MarkProductBatch.MARK_PRODUCT_BATCH,
            MarkProductCycle.MARK_PRODUCT_CYCLE,
            MarkProductCycleExpense.MARK_PRODUCT_CYCLE_EXPENSE,
            MarkProductMarket.MARK_PRODUCT_MARKET,
            MarkProductRisk.MARK_PRODUCT_RISK,
            MisAccountBill.MIS_ACCOUNT_BILL,
            MisAccountTitle.MIS_ACCOUNT_TITLE,
            MisBankAccount.MIS_BANK_ACCOUNT,
            MisContract.MIS_CONTRACT,
            MisProductionOrder.MIS_PRODUCTION_ORDER,
            MisProductionOrderItem.MIS_PRODUCTION_ORDER_ITEM,
            MisPurchaseOrder.MIS_PURCHASE_ORDER,
            MisPurchaseOrderItem.MIS_PURCHASE_ORDER_ITEM,
            MisSaleOrder.MIS_SALE_ORDER,
            MisSaleOrderItem.MIS_SALE_ORDER_ITEM,
            MisStock.MIS_STOCK,
            MisStockItem.MIS_STOCK_ITEM,
            MisStockPlace.MIS_STOCK_PLACE,
            MisStockPlaceItem.MIS_STOCK_PLACE_ITEM,
            MisStockPlaceItemSub.MIS_STOCK_PLACE_ITEM_SUB,
            MisStore.MIS_STORE,
            MisStoreItem.MIS_STORE_ITEM,
            Oauth2Authorization.OAUTH2_AUTHORIZATION,
            Oauth2RegisteredClient.OAUTH2_REGISTERED_CLIENT,
            Product.PRODUCT,
            SysConst.SYS_CONST,
            SysConstItem.SYS_CONST_ITEM,
            SysMenu.SYS_MENU,
            SysMenuAction.SYS_MENU_ACTION,
            Users.USERS
        );
    }
}
