server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_agri
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO