/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.records;


import com.agri.mis.db.tables.BatchRisk;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchRiskRecord extends UpdatableRecordImpl<BatchRiskRecord> implements Record14<Long, Long, Long, String, String, String, String, BigDecimal, Long, String, LocalDate, LocalDateTime, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.batch_risk.id</code>.
     */
    public BatchRiskRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.batch_risk.product_id</code>.
     */
    public BatchRiskRecord setProductId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.batch_risk.batch_id</code>.
     */
    public BatchRiskRecord setBatchId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.batch_id</code>.
     */
    public Long getBatchId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.batch_risk.cycle_name</code>.
     */
    public BatchRiskRecord setCycleName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.cycle_name</code>.
     */
    public String getCycleName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.batch_risk.risk_category</code>.
     */
    public BatchRiskRecord setRiskCategory(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.risk_category</code>.
     */
    public String getRiskCategory() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.batch_risk.description</code>.
     */
    public BatchRiskRecord setDescription(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.batch_risk.solution</code>.
     */
    public BatchRiskRecord setSolution(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.solution</code>.
     */
    public String getSolution() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.batch_risk.fee_amount</code>.
     */
    public BatchRiskRecord setFeeAmount(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.fee_amount</code>.
     */
    public BigDecimal getFeeAmount() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.batch_risk.created_user_id</code>.
     */
    public BatchRiskRecord setCreatedUserId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.created_user_id</code>.
     */
    public Long getCreatedUserId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.batch_risk.created_by</code>.
     */
    public BatchRiskRecord setCreatedBy(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.batch_risk.occur_date</code>.
     */
    public BatchRiskRecord setOccurDate(LocalDate value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.occur_date</code>.
     */
    public LocalDate getOccurDate() {
        return (LocalDate) get(10);
    }

    /**
     * Setter for <code>public.batch_risk.created_at</code>.
     */
    public BatchRiskRecord setCreatedAt(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.batch_risk.corp_id</code>.
     */
    public BatchRiskRecord setCorpId(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.corp_id</code>.
     */
    public Long getCorpId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.batch_risk.name</code>.
     */
    public BatchRiskRecord setName(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.name</code>.
     */
    public String getName() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, Long, Long, String, String, String, String, BigDecimal, Long, String, LocalDate, LocalDateTime, Long, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, Long, Long, String, String, String, String, BigDecimal, Long, String, LocalDate, LocalDateTime, Long, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BatchRisk.BATCH_RISK.ID;
    }

    @Override
    public Field<Long> field2() {
        return BatchRisk.BATCH_RISK.PRODUCT_ID;
    }

    @Override
    public Field<Long> field3() {
        return BatchRisk.BATCH_RISK.BATCH_ID;
    }

    @Override
    public Field<String> field4() {
        return BatchRisk.BATCH_RISK.CYCLE_NAME;
    }

    @Override
    public Field<String> field5() {
        return BatchRisk.BATCH_RISK.RISK_CATEGORY;
    }

    @Override
    public Field<String> field6() {
        return BatchRisk.BATCH_RISK.DESCRIPTION;
    }

    @Override
    public Field<String> field7() {
        return BatchRisk.BATCH_RISK.SOLUTION;
    }

    @Override
    public Field<BigDecimal> field8() {
        return BatchRisk.BATCH_RISK.FEE_AMOUNT;
    }

    @Override
    public Field<Long> field9() {
        return BatchRisk.BATCH_RISK.CREATED_USER_ID;
    }

    @Override
    public Field<String> field10() {
        return BatchRisk.BATCH_RISK.CREATED_BY;
    }

    @Override
    public Field<LocalDate> field11() {
        return BatchRisk.BATCH_RISK.OCCUR_DATE;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return BatchRisk.BATCH_RISK.CREATED_AT;
    }

    @Override
    public Field<Long> field13() {
        return BatchRisk.BATCH_RISK.CORP_ID;
    }

    @Override
    public Field<String> field14() {
        return BatchRisk.BATCH_RISK.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getProductId();
    }

    @Override
    public Long component3() {
        return getBatchId();
    }

    @Override
    public String component4() {
        return getCycleName();
    }

    @Override
    public String component5() {
        return getRiskCategory();
    }

    @Override
    public String component6() {
        return getDescription();
    }

    @Override
    public String component7() {
        return getSolution();
    }

    @Override
    public BigDecimal component8() {
        return getFeeAmount();
    }

    @Override
    public Long component9() {
        return getCreatedUserId();
    }

    @Override
    public String component10() {
        return getCreatedBy();
    }

    @Override
    public LocalDate component11() {
        return getOccurDate();
    }

    @Override
    public LocalDateTime component12() {
        return getCreatedAt();
    }

    @Override
    public Long component13() {
        return getCorpId();
    }

    @Override
    public String component14() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getProductId();
    }

    @Override
    public Long value3() {
        return getBatchId();
    }

    @Override
    public String value4() {
        return getCycleName();
    }

    @Override
    public String value5() {
        return getRiskCategory();
    }

    @Override
    public String value6() {
        return getDescription();
    }

    @Override
    public String value7() {
        return getSolution();
    }

    @Override
    public BigDecimal value8() {
        return getFeeAmount();
    }

    @Override
    public Long value9() {
        return getCreatedUserId();
    }

    @Override
    public String value10() {
        return getCreatedBy();
    }

    @Override
    public LocalDate value11() {
        return getOccurDate();
    }

    @Override
    public LocalDateTime value12() {
        return getCreatedAt();
    }

    @Override
    public Long value13() {
        return getCorpId();
    }

    @Override
    public String value14() {
        return getName();
    }

    @Override
    public BatchRiskRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BatchRiskRecord value2(Long value) {
        setProductId(value);
        return this;
    }

    @Override
    public BatchRiskRecord value3(Long value) {
        setBatchId(value);
        return this;
    }

    @Override
    public BatchRiskRecord value4(String value) {
        setCycleName(value);
        return this;
    }

    @Override
    public BatchRiskRecord value5(String value) {
        setRiskCategory(value);
        return this;
    }

    @Override
    public BatchRiskRecord value6(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public BatchRiskRecord value7(String value) {
        setSolution(value);
        return this;
    }

    @Override
    public BatchRiskRecord value8(BigDecimal value) {
        setFeeAmount(value);
        return this;
    }

    @Override
    public BatchRiskRecord value9(Long value) {
        setCreatedUserId(value);
        return this;
    }

    @Override
    public BatchRiskRecord value10(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public BatchRiskRecord value11(LocalDate value) {
        setOccurDate(value);
        return this;
    }

    @Override
    public BatchRiskRecord value12(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public BatchRiskRecord value13(Long value) {
        setCorpId(value);
        return this;
    }

    @Override
    public BatchRiskRecord value14(String value) {
        setName(value);
        return this;
    }

    @Override
    public BatchRiskRecord values(Long value1, Long value2, Long value3, String value4, String value5, String value6, String value7, BigDecimal value8, Long value9, String value10, LocalDate value11, LocalDateTime value12, Long value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchRiskRecord
     */
    public BatchRiskRecord() {
        super(BatchRisk.BATCH_RISK);
    }

    /**
     * Create a detached, initialised BatchRiskRecord
     */
    public BatchRiskRecord(Long id, Long productId, Long batchId, String cycleName, String riskCategory, String description, String solution, BigDecimal feeAmount, Long createdUserId, String createdBy, LocalDate occurDate, LocalDateTime createdAt, Long corpId, String name) {
        super(BatchRisk.BATCH_RISK);

        setId(id);
        setProductId(productId);
        setBatchId(batchId);
        setCycleName(cycleName);
        setRiskCategory(riskCategory);
        setDescription(description);
        setSolution(solution);
        setFeeAmount(feeAmount);
        setCreatedUserId(createdUserId);
        setCreatedBy(createdBy);
        setOccurDate(occurDate);
        setCreatedAt(createdAt);
        setCorpId(corpId);
        setName(name);
    }

    /**
     * Create a detached, initialised BatchRiskRecord
     */
    public BatchRiskRecord(com.agri.mis.db.tables.pojos.BatchRisk value) {
        super(BatchRisk.BATCH_RISK);

        if (value != null) {
            setId(value.getId());
            setProductId(value.getProductId());
            setBatchId(value.getBatchId());
            setCycleName(value.getCycleName());
            setRiskCategory(value.getRiskCategory());
            setDescription(value.getDescription());
            setSolution(value.getSolution());
            setFeeAmount(value.getFeeAmount());
            setCreatedUserId(value.getCreatedUserId());
            setCreatedBy(value.getCreatedBy());
            setOccurDate(value.getOccurDate());
            setCreatedAt(value.getCreatedAt());
            setCorpId(value.getCorpId());
            setName(value.getName());
        }
    }
}
