/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.records;


import com.agri.mis.db.tables.CheckTempItem;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckTempItemRecord extends UpdatableRecordImpl<CheckTempItemRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.check_temp_item.id</code>.
     */
    public CheckTempItemRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.check_temp_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.check_temp_item.check_temp_id</code>.
     */
    public CheckTempItemRecord setCheckTempId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.check_temp_item.check_temp_id</code>.
     */
    public Long getCheckTempId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.check_temp_item.user_id</code>.
     */
    public CheckTempItemRecord setUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.check_temp_item.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CheckTempItem.CHECK_TEMP_ITEM.ID;
    }

    @Override
    public Field<Long> field2() {
        return CheckTempItem.CHECK_TEMP_ITEM.CHECK_TEMP_ID;
    }

    @Override
    public Field<Long> field3() {
        return CheckTempItem.CHECK_TEMP_ITEM.USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCheckTempId();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCheckTempId();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public CheckTempItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CheckTempItemRecord value2(Long value) {
        setCheckTempId(value);
        return this;
    }

    @Override
    public CheckTempItemRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public CheckTempItemRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CheckTempItemRecord
     */
    public CheckTempItemRecord() {
        super(CheckTempItem.CHECK_TEMP_ITEM);
    }

    /**
     * Create a detached, initialised CheckTempItemRecord
     */
    public CheckTempItemRecord(Long id, Long checkTempId, Long userId) {
        super(CheckTempItem.CHECK_TEMP_ITEM);

        setId(id);
        setCheckTempId(checkTempId);
        setUserId(userId);
    }

    /**
     * Create a detached, initialised CheckTempItemRecord
     */
    public CheckTempItemRecord(com.agri.mis.db.tables.pojos.CheckTempItem value) {
        super(CheckTempItem.CHECK_TEMP_ITEM);

        if (value != null) {
            setId(value.getId());
            setCheckTempId(value.getCheckTempId());
            setUserId(value.getUserId());
        }
    }
}
