/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.records;


import com.agri.mis.db.tables.CmsCategory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsCategoryRecord extends UpdatableRecordImpl<CmsCategoryRecord> implements Record5<Long, String, String, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cms_category.id</code>.
     */
    public CmsCategoryRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_category.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.cms_category.code</code>.
     */
    public CmsCategoryRecord setCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_category.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.cms_category.name</code>.
     */
    public CmsCategoryRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_category.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.cms_category.parent_id</code>.
     */
    public CmsCategoryRecord setParentId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_category.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.cms_category.corp_id</code>.
     */
    public CmsCategoryRecord setCorpId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_category.corp_id</code>.
     */
    public Long getCorpId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CmsCategory.CMS_CATEGORY.ID;
    }

    @Override
    public Field<String> field2() {
        return CmsCategory.CMS_CATEGORY.CODE;
    }

    @Override
    public Field<String> field3() {
        return CmsCategory.CMS_CATEGORY.NAME;
    }

    @Override
    public Field<Long> field4() {
        return CmsCategory.CMS_CATEGORY.PARENT_ID;
    }

    @Override
    public Field<Long> field5() {
        return CmsCategory.CMS_CATEGORY.CORP_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Long component4() {
        return getParentId();
    }

    @Override
    public Long component5() {
        return getCorpId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Long value4() {
        return getParentId();
    }

    @Override
    public Long value5() {
        return getCorpId();
    }

    @Override
    public CmsCategoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CmsCategoryRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public CmsCategoryRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public CmsCategoryRecord value4(Long value) {
        setParentId(value);
        return this;
    }

    @Override
    public CmsCategoryRecord value5(Long value) {
        setCorpId(value);
        return this;
    }

    @Override
    public CmsCategoryRecord values(Long value1, String value2, String value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CmsCategoryRecord
     */
    public CmsCategoryRecord() {
        super(CmsCategory.CMS_CATEGORY);
    }

    /**
     * Create a detached, initialised CmsCategoryRecord
     */
    public CmsCategoryRecord(Long id, String code, String name, Long parentId, Long corpId) {
        super(CmsCategory.CMS_CATEGORY);

        setId(id);
        setCode(code);
        setName(name);
        setParentId(parentId);
        setCorpId(corpId);
    }

    /**
     * Create a detached, initialised CmsCategoryRecord
     */
    public CmsCategoryRecord(com.agri.mis.db.tables.pojos.CmsCategory value) {
        super(CmsCategory.CMS_CATEGORY);

        if (value != null) {
            setId(value.getId());
            setCode(value.getCode());
            setName(value.getName());
            setParentId(value.getParentId());
            setCorpId(value.getCorpId());
        }
    }
}
