/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.records;


import com.agri.mis.db.tables.CmsVideo;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsVideoRecord extends UpdatableRecordImpl<CmsVideoRecord> implements Record15<Long, String, Short, Short, String, Integer, Integer, Long, LocalDateTime, Short, String, String, Long, LocalDate, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cms_video.id</code>.
     */
    public CmsVideoRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.cms_video.title</code>.
     */
    public CmsVideoRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.cms_video.status</code>.
     */
    public CmsVideoRecord setStatus(Short value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.status</code>.
     */
    public Short getStatus() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.cms_video.check_status</code>.
     */
    public CmsVideoRecord setCheckStatus(Short value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.check_status</code>.
     */
    public Short getCheckStatus() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.cms_video.author</code>.
     */
    public CmsVideoRecord setAuthor(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.author</code>.
     */
    public String getAuthor() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.cms_video.prise_up</code>.
     */
    public CmsVideoRecord setPriseUp(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.prise_up</code>.
     */
    public Integer getPriseUp() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.cms_video.prise_down</code>.
     */
    public CmsVideoRecord setPriseDown(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.prise_down</code>.
     */
    public Integer getPriseDown() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.cms_video.category_id</code>.
     */
    public CmsVideoRecord setCategoryId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.cms_video.created_at</code>.
     */
    public CmsVideoRecord setCreatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.cms_video.created_by</code>.
     */
    public CmsVideoRecord setCreatedBy(Short value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.created_by</code>.
     */
    public Short getCreatedBy() {
        return (Short) get(9);
    }

    /**
     * Setter for <code>public.cms_video.tags</code>.
     */
    public CmsVideoRecord setTags(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.tags</code>.
     */
    public String getTags() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.cms_video.description</code>.
     */
    public CmsVideoRecord setDescription(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.description</code>.
     */
    public String getDescription() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.cms_video.created_user_id</code>.
     */
    public CmsVideoRecord setCreatedUserId(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.created_user_id</code>.
     */
    public Long getCreatedUserId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.cms_video.publish_at</code>.
     */
    public CmsVideoRecord setPublishAt(LocalDate value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.publish_at</code>.
     */
    public LocalDate getPublishAt() {
        return (LocalDate) get(13);
    }

    /**
     * Setter for <code>public.cms_video.image_url</code>.
     */
    public CmsVideoRecord setImageUrl(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.cms_video.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, String, Short, Short, String, Integer, Integer, Long, LocalDateTime, Short, String, String, Long, LocalDate, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Long, String, Short, Short, String, Integer, Integer, Long, LocalDateTime, Short, String, String, Long, LocalDate, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CmsVideo.CMS_VIDEO.ID;
    }

    @Override
    public Field<String> field2() {
        return CmsVideo.CMS_VIDEO.TITLE;
    }

    @Override
    public Field<Short> field3() {
        return CmsVideo.CMS_VIDEO.STATUS;
    }

    @Override
    public Field<Short> field4() {
        return CmsVideo.CMS_VIDEO.CHECK_STATUS;
    }

    @Override
    public Field<String> field5() {
        return CmsVideo.CMS_VIDEO.AUTHOR;
    }

    @Override
    public Field<Integer> field6() {
        return CmsVideo.CMS_VIDEO.PRISE_UP;
    }

    @Override
    public Field<Integer> field7() {
        return CmsVideo.CMS_VIDEO.PRISE_DOWN;
    }

    @Override
    public Field<Long> field8() {
        return CmsVideo.CMS_VIDEO.CATEGORY_ID;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return CmsVideo.CMS_VIDEO.CREATED_AT;
    }

    @Override
    public Field<Short> field10() {
        return CmsVideo.CMS_VIDEO.CREATED_BY;
    }

    @Override
    public Field<String> field11() {
        return CmsVideo.CMS_VIDEO.TAGS;
    }

    @Override
    public Field<String> field12() {
        return CmsVideo.CMS_VIDEO.DESCRIPTION;
    }

    @Override
    public Field<Long> field13() {
        return CmsVideo.CMS_VIDEO.CREATED_USER_ID;
    }

    @Override
    public Field<LocalDate> field14() {
        return CmsVideo.CMS_VIDEO.PUBLISH_AT;
    }

    @Override
    public Field<String> field15() {
        return CmsVideo.CMS_VIDEO.IMAGE_URL;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public Short component3() {
        return getStatus();
    }

    @Override
    public Short component4() {
        return getCheckStatus();
    }

    @Override
    public String component5() {
        return getAuthor();
    }

    @Override
    public Integer component6() {
        return getPriseUp();
    }

    @Override
    public Integer component7() {
        return getPriseDown();
    }

    @Override
    public Long component8() {
        return getCategoryId();
    }

    @Override
    public LocalDateTime component9() {
        return getCreatedAt();
    }

    @Override
    public Short component10() {
        return getCreatedBy();
    }

    @Override
    public String component11() {
        return getTags();
    }

    @Override
    public String component12() {
        return getDescription();
    }

    @Override
    public Long component13() {
        return getCreatedUserId();
    }

    @Override
    public LocalDate component14() {
        return getPublishAt();
    }

    @Override
    public String component15() {
        return getImageUrl();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public Short value3() {
        return getStatus();
    }

    @Override
    public Short value4() {
        return getCheckStatus();
    }

    @Override
    public String value5() {
        return getAuthor();
    }

    @Override
    public Integer value6() {
        return getPriseUp();
    }

    @Override
    public Integer value7() {
        return getPriseDown();
    }

    @Override
    public Long value8() {
        return getCategoryId();
    }

    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    @Override
    public Short value10() {
        return getCreatedBy();
    }

    @Override
    public String value11() {
        return getTags();
    }

    @Override
    public String value12() {
        return getDescription();
    }

    @Override
    public Long value13() {
        return getCreatedUserId();
    }

    @Override
    public LocalDate value14() {
        return getPublishAt();
    }

    @Override
    public String value15() {
        return getImageUrl();
    }

    @Override
    public CmsVideoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CmsVideoRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public CmsVideoRecord value3(Short value) {
        setStatus(value);
        return this;
    }

    @Override
    public CmsVideoRecord value4(Short value) {
        setCheckStatus(value);
        return this;
    }

    @Override
    public CmsVideoRecord value5(String value) {
        setAuthor(value);
        return this;
    }

    @Override
    public CmsVideoRecord value6(Integer value) {
        setPriseUp(value);
        return this;
    }

    @Override
    public CmsVideoRecord value7(Integer value) {
        setPriseDown(value);
        return this;
    }

    @Override
    public CmsVideoRecord value8(Long value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public CmsVideoRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CmsVideoRecord value10(Short value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public CmsVideoRecord value11(String value) {
        setTags(value);
        return this;
    }

    @Override
    public CmsVideoRecord value12(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CmsVideoRecord value13(Long value) {
        setCreatedUserId(value);
        return this;
    }

    @Override
    public CmsVideoRecord value14(LocalDate value) {
        setPublishAt(value);
        return this;
    }

    @Override
    public CmsVideoRecord value15(String value) {
        setImageUrl(value);
        return this;
    }

    @Override
    public CmsVideoRecord values(Long value1, String value2, Short value3, Short value4, String value5, Integer value6, Integer value7, Long value8, LocalDateTime value9, Short value10, String value11, String value12, Long value13, LocalDate value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CmsVideoRecord
     */
    public CmsVideoRecord() {
        super(CmsVideo.CMS_VIDEO);
    }

    /**
     * Create a detached, initialised CmsVideoRecord
     */
    public CmsVideoRecord(Long id, String title, Short status, Short checkStatus, String author, Integer priseUp, Integer priseDown, Long categoryId, LocalDateTime createdAt, Short createdBy, String tags, String description, Long createdUserId, LocalDate publishAt, String imageUrl) {
        super(CmsVideo.CMS_VIDEO);

        setId(id);
        setTitle(title);
        setStatus(status);
        setCheckStatus(checkStatus);
        setAuthor(author);
        setPriseUp(priseUp);
        setPriseDown(priseDown);
        setCategoryId(categoryId);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setTags(tags);
        setDescription(description);
        setCreatedUserId(createdUserId);
        setPublishAt(publishAt);
        setImageUrl(imageUrl);
    }

    /**
     * Create a detached, initialised CmsVideoRecord
     */
    public CmsVideoRecord(com.agri.mis.db.tables.pojos.CmsVideo value) {
        super(CmsVideo.CMS_VIDEO);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setStatus(value.getStatus());
            setCheckStatus(value.getCheckStatus());
            setAuthor(value.getAuthor());
            setPriseUp(value.getPriseUp());
            setPriseDown(value.getPriseDown());
            setCategoryId(value.getCategoryId());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setTags(value.getTags());
            setDescription(value.getDescription());
            setCreatedUserId(value.getCreatedUserId());
            setPublishAt(value.getPublishAt());
            setImageUrl(value.getImageUrl());
        }
    }
}
