/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.records;


import com.agri.mis.db.tables.CorpManager;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorpManagerRecord extends UpdatableRecordImpl<CorpManagerRecord> implements Record6<Long, Long, Boolean, Long, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.corp_manager.id</code>.
     */
    public CorpManagerRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.corp_manager.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.corp_manager.user_id</code>.
     */
    public CorpManagerRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.corp_manager.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.corp_manager.is_manager</code>.
     */
    public CorpManagerRecord setIsManager(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.corp_manager.is_manager</code>.
     */
    public Boolean getIsManager() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.corp_manager.corp_id</code>.
     */
    public CorpManagerRecord setCorpId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.corp_manager.corp_id</code>.
     */
    public Long getCorpId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.corp_manager.created_at</code>.
     */
    public CorpManagerRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.corp_manager.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.corp_manager.position</code>.
     */
    public CorpManagerRecord setPosition(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.corp_manager.position</code>.
     */
    public String getPosition() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Boolean, Long, LocalDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Boolean, Long, LocalDateTime, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CorpManager.CORP_MANAGER.ID;
    }

    @Override
    public Field<Long> field2() {
        return CorpManager.CORP_MANAGER.USER_ID;
    }

    @Override
    public Field<Boolean> field3() {
        return CorpManager.CORP_MANAGER.IS_MANAGER;
    }

    @Override
    public Field<Long> field4() {
        return CorpManager.CORP_MANAGER.CORP_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return CorpManager.CORP_MANAGER.CREATED_AT;
    }

    @Override
    public Field<String> field6() {
        return CorpManager.CORP_MANAGER.POSITION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Boolean component3() {
        return getIsManager();
    }

    @Override
    public Long component4() {
        return getCorpId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public String component6() {
        return getPosition();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Boolean value3() {
        return getIsManager();
    }

    @Override
    public Long value4() {
        return getCorpId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public String value6() {
        return getPosition();
    }

    @Override
    public CorpManagerRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CorpManagerRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public CorpManagerRecord value3(Boolean value) {
        setIsManager(value);
        return this;
    }

    @Override
    public CorpManagerRecord value4(Long value) {
        setCorpId(value);
        return this;
    }

    @Override
    public CorpManagerRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CorpManagerRecord value6(String value) {
        setPosition(value);
        return this;
    }

    @Override
    public CorpManagerRecord values(Long value1, Long value2, Boolean value3, Long value4, LocalDateTime value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CorpManagerRecord
     */
    public CorpManagerRecord() {
        super(CorpManager.CORP_MANAGER);
    }

    /**
     * Create a detached, initialised CorpManagerRecord
     */
    public CorpManagerRecord(Long id, Long userId, Boolean isManager, Long corpId, LocalDateTime createdAt, String position) {
        super(CorpManager.CORP_MANAGER);

        setId(id);
        setUserId(userId);
        setIsManager(isManager);
        setCorpId(corpId);
        setCreatedAt(createdAt);
        setPosition(position);
    }

    /**
     * Create a detached, initialised CorpManagerRecord
     */
    public CorpManagerRecord(com.agri.mis.db.tables.pojos.CorpManager value) {
        super(CorpManager.CORP_MANAGER);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setIsManager(value.getIsManager());
            setCorpId(value.getCorpId());
            setCreatedAt(value.getCreatedAt());
            setPosition(value.getPosition());
        }
    }
}
