/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.records;


import com.agri.mis.db.tables.Corp;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorpRecord extends UpdatableRecordImpl<CorpRecord> implements Record6<Long, String, String, String, Long, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.corp.id</code>.
     */
    public CorpRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.corp.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.corp.name</code>.
     */
    public CorpRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.corp.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.corp.code</code>.
     */
    public CorpRecord setCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.corp.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.corp.description</code>.
     */
    public CorpRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.corp.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.corp.address_id</code>.
     */
    public CorpRecord setAddressId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.corp.address_id</code>.
     */
    public Long getAddressId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.corp.created_at</code>.
     */
    public CorpRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.corp.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, Long, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, Long, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Corp.CORP.ID;
    }

    @Override
    public Field<String> field2() {
        return Corp.CORP.NAME;
    }

    @Override
    public Field<String> field3() {
        return Corp.CORP.CODE;
    }

    @Override
    public Field<String> field4() {
        return Corp.CORP.DESCRIPTION;
    }

    @Override
    public Field<Long> field5() {
        return Corp.CORP.ADDRESS_ID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Corp.CORP.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Long component5() {
        return getAddressId();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public Long value5() {
        return getAddressId();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public CorpRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CorpRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CorpRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public CorpRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CorpRecord value5(Long value) {
        setAddressId(value);
        return this;
    }

    @Override
    public CorpRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CorpRecord values(Long value1, String value2, String value3, String value4, Long value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CorpRecord
     */
    public CorpRecord() {
        super(Corp.CORP);
    }

    /**
     * Create a detached, initialised CorpRecord
     */
    public CorpRecord(Long id, String name, String code, String description, Long addressId, LocalDateTime createdAt) {
        super(Corp.CORP);

        setId(id);
        setName(name);
        setCode(code);
        setDescription(description);
        setAddressId(addressId);
        setCreatedAt(createdAt);
    }

    /**
     * Create a detached, initialised CorpRecord
     */
    public CorpRecord(com.agri.mis.db.tables.pojos.Corp value) {
        super(Corp.CORP);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setCode(value.getCode());
            setDescription(value.getDescription());
            setAddressId(value.getAddressId());
            setCreatedAt(value.getCreatedAt());
        }
    }
}
