/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.records;


import com.agri.mis.db.tables.Customer;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> implements Record9<Long, String, String, String, Long, LocalDateTime, Long, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.customer.id</code>.
     */
    public CustomerRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.customer.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.customer.name</code>.
     */
    public CustomerRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.customer.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.customer.code</code>.
     */
    public CustomerRecord setCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.customer.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.customer.description</code>.
     */
    public CustomerRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.customer.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.customer.address_id</code>.
     */
    public CustomerRecord setAddressId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.customer.address_id</code>.
     */
    public Long getAddressId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.customer.created_at</code>.
     */
    public CustomerRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.customer.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.customer.corp_id</code>.
     */
    public CustomerRecord setCorpId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.customer.corp_id</code>.
     */
    public Long getCorpId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.customer.is_customer</code>.
     */
    public CustomerRecord setIsCustomer(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.customer.is_customer</code>.
     */
    public Boolean getIsCustomer() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.customer.is_supply</code>.
     */
    public CustomerRecord setIsSupply(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.customer.is_supply</code>.
     */
    public Boolean getIsSupply() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, Long, LocalDateTime, Long, Boolean, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, Long, LocalDateTime, Long, Boolean, Boolean> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Customer.CUSTOMER.ID;
    }

    @Override
    public Field<String> field2() {
        return Customer.CUSTOMER.NAME;
    }

    @Override
    public Field<String> field3() {
        return Customer.CUSTOMER.CODE;
    }

    @Override
    public Field<String> field4() {
        return Customer.CUSTOMER.DESCRIPTION;
    }

    @Override
    public Field<Long> field5() {
        return Customer.CUSTOMER.ADDRESS_ID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Customer.CUSTOMER.CREATED_AT;
    }

    @Override
    public Field<Long> field7() {
        return Customer.CUSTOMER.CORP_ID;
    }

    @Override
    public Field<Boolean> field8() {
        return Customer.CUSTOMER.IS_CUSTOMER;
    }

    @Override
    public Field<Boolean> field9() {
        return Customer.CUSTOMER.IS_SUPPLY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Long component5() {
        return getAddressId();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public Long component7() {
        return getCorpId();
    }

    @Override
    public Boolean component8() {
        return getIsCustomer();
    }

    @Override
    public Boolean component9() {
        return getIsSupply();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public Long value5() {
        return getAddressId();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public Long value7() {
        return getCorpId();
    }

    @Override
    public Boolean value8() {
        return getIsCustomer();
    }

    @Override
    public Boolean value9() {
        return getIsSupply();
    }

    @Override
    public CustomerRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CustomerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CustomerRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public CustomerRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CustomerRecord value5(Long value) {
        setAddressId(value);
        return this;
    }

    @Override
    public CustomerRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CustomerRecord value7(Long value) {
        setCorpId(value);
        return this;
    }

    @Override
    public CustomerRecord value8(Boolean value) {
        setIsCustomer(value);
        return this;
    }

    @Override
    public CustomerRecord value9(Boolean value) {
        setIsSupply(value);
        return this;
    }

    @Override
    public CustomerRecord values(Long value1, String value2, String value3, String value4, Long value5, LocalDateTime value6, Long value7, Boolean value8, Boolean value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(Long id, String name, String code, String description, Long addressId, LocalDateTime createdAt, Long corpId, Boolean isCustomer, Boolean isSupply) {
        super(Customer.CUSTOMER);

        setId(id);
        setName(name);
        setCode(code);
        setDescription(description);
        setAddressId(addressId);
        setCreatedAt(createdAt);
        setCorpId(corpId);
        setIsCustomer(isCustomer);
        setIsSupply(isSupply);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(com.agri.mis.db.tables.pojos.Customer value) {
        super(Customer.CUSTOMER);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setCode(value.getCode());
            setDescription(value.getDescription());
            setAddressId(value.getAddressId());
            setCreatedAt(value.getCreatedAt());
            setCorpId(value.getCorpId());
            setIsCustomer(value.getIsCustomer());
            setIsSupply(value.getIsSupply());
        }
    }
}
