/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.records;


import com.agri.mis.db.tables.MisStoreItem;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MisStoreItemRecord extends UpdatableRecordImpl<MisStoreItemRecord> implements Record11<Long, Long, BigDecimal, Long, Long, BigDecimal, BigDecimal, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mis_store_item.id</code>.
     */
    public MisStoreItemRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mis_store_item.product_id</code>.
     */
    public MisStoreItemRecord setProductId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mis_store_item.quantity</code>.
     */
    public MisStoreItemRecord setQuantity(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.mis_store_item.store_id</code>.
     */
    public MisStoreItemRecord setStoreId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.store_id</code>.
     */
    public Long getStoreId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.mis_store_item.corp_id</code>.
     */
    public MisStoreItemRecord setCorpId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.corp_id</code>.
     */
    public Long getCorpId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.mis_store_item.price</code>.
     */
    public MisStoreItemRecord setPrice(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.mis_store_item.amount</code>.
     */
    public MisStoreItemRecord setAmount(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.mis_store_item.created_at</code>.
     */
    public MisStoreItemRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.mis_store_item.created_by</code>.
     */
    public MisStoreItemRecord setCreatedBy(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.mis_store_item.updated_at</code>.
     */
    public MisStoreItemRecord setUpdatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.mis_store_item.updated_by</code>.
     */
    public MisStoreItemRecord setUpdatedBy(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_store_item.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Long, BigDecimal, Long, Long, BigDecimal, BigDecimal, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, Long, BigDecimal, Long, Long, BigDecimal, BigDecimal, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MisStoreItem.MIS_STORE_ITEM.ID;
    }

    @Override
    public Field<Long> field2() {
        return MisStoreItem.MIS_STORE_ITEM.PRODUCT_ID;
    }

    @Override
    public Field<BigDecimal> field3() {
        return MisStoreItem.MIS_STORE_ITEM.QUANTITY;
    }

    @Override
    public Field<Long> field4() {
        return MisStoreItem.MIS_STORE_ITEM.STORE_ID;
    }

    @Override
    public Field<Long> field5() {
        return MisStoreItem.MIS_STORE_ITEM.CORP_ID;
    }

    @Override
    public Field<BigDecimal> field6() {
        return MisStoreItem.MIS_STORE_ITEM.PRICE;
    }

    @Override
    public Field<BigDecimal> field7() {
        return MisStoreItem.MIS_STORE_ITEM.AMOUNT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return MisStoreItem.MIS_STORE_ITEM.CREATED_AT;
    }

    @Override
    public Field<String> field9() {
        return MisStoreItem.MIS_STORE_ITEM.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return MisStoreItem.MIS_STORE_ITEM.UPDATED_AT;
    }

    @Override
    public Field<String> field11() {
        return MisStoreItem.MIS_STORE_ITEM.UPDATED_BY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getProductId();
    }

    @Override
    public BigDecimal component3() {
        return getQuantity();
    }

    @Override
    public Long component4() {
        return getStoreId();
    }

    @Override
    public Long component5() {
        return getCorpId();
    }

    @Override
    public BigDecimal component6() {
        return getPrice();
    }

    @Override
    public BigDecimal component7() {
        return getAmount();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public String component9() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component10() {
        return getUpdatedAt();
    }

    @Override
    public String component11() {
        return getUpdatedBy();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getProductId();
    }

    @Override
    public BigDecimal value3() {
        return getQuantity();
    }

    @Override
    public Long value4() {
        return getStoreId();
    }

    @Override
    public Long value5() {
        return getCorpId();
    }

    @Override
    public BigDecimal value6() {
        return getPrice();
    }

    @Override
    public BigDecimal value7() {
        return getAmount();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public String value9() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value10() {
        return getUpdatedAt();
    }

    @Override
    public String value11() {
        return getUpdatedBy();
    }

    @Override
    public MisStoreItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MisStoreItemRecord value2(Long value) {
        setProductId(value);
        return this;
    }

    @Override
    public MisStoreItemRecord value3(BigDecimal value) {
        setQuantity(value);
        return this;
    }

    @Override
    public MisStoreItemRecord value4(Long value) {
        setStoreId(value);
        return this;
    }

    @Override
    public MisStoreItemRecord value5(Long value) {
        setCorpId(value);
        return this;
    }

    @Override
    public MisStoreItemRecord value6(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public MisStoreItemRecord value7(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public MisStoreItemRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MisStoreItemRecord value9(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public MisStoreItemRecord value10(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public MisStoreItemRecord value11(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public MisStoreItemRecord values(Long value1, Long value2, BigDecimal value3, Long value4, Long value5, BigDecimal value6, BigDecimal value7, LocalDateTime value8, String value9, LocalDateTime value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MisStoreItemRecord
     */
    public MisStoreItemRecord() {
        super(MisStoreItem.MIS_STORE_ITEM);
    }

    /**
     * Create a detached, initialised MisStoreItemRecord
     */
    public MisStoreItemRecord(Long id, Long productId, BigDecimal quantity, Long storeId, Long corpId, BigDecimal price, BigDecimal amount, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy) {
        super(MisStoreItem.MIS_STORE_ITEM);

        setId(id);
        setProductId(productId);
        setQuantity(quantity);
        setStoreId(storeId);
        setCorpId(corpId);
        setPrice(price);
        setAmount(amount);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
    }

    /**
     * Create a detached, initialised MisStoreItemRecord
     */
    public MisStoreItemRecord(com.agri.mis.db.tables.pojos.MisStoreItem value) {
        super(MisStoreItem.MIS_STORE_ITEM);

        if (value != null) {
            setId(value.getId());
            setProductId(value.getProductId());
            setQuantity(value.getQuantity());
            setStoreId(value.getStoreId());
            setCorpId(value.getCorpId());
            setPrice(value.getPrice());
            setAmount(value.getAmount());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
        }
    }
}
