/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.records;


import com.agri.mis.db.tables.MisSaleOrderItem;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MisSaleOrderItemRecord extends UpdatableRecordImpl<MisSaleOrderItemRecord> implements Record12<Long, Long, BigDecimal, BigDecimal, Long, Long, LocalDateTime, String, LocalDateTime, String, Long, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mis_sale_order_item.id</code>.
     */
    public MisSaleOrderItemRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.product_id</code>.
     */
    public MisSaleOrderItemRecord setProductId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.quantity</code>.
     */
    public MisSaleOrderItemRecord setQuantity(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.price</code>.
     */
    public MisSaleOrderItemRecord setPrice(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.customer_id</code>.
     */
    public MisSaleOrderItemRecord setCustomerId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.customer_id</code>.
     */
    public Long getCustomerId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.sale_order_id</code>.
     */
    public MisSaleOrderItemRecord setSaleOrderId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.sale_order_id</code>.
     */
    public Long getSaleOrderId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.created_at</code>.
     */
    public MisSaleOrderItemRecord setCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.created_by</code>.
     */
    public MisSaleOrderItemRecord setCreatedBy(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.updted_at</code>.
     */
    public MisSaleOrderItemRecord setUpdtedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.updted_at</code>.
     */
    public LocalDateTime getUpdtedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.updated_by</code>.
     */
    public MisSaleOrderItemRecord setUpdatedBy(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.corp_id</code>.
     */
    public MisSaleOrderItemRecord setCorpId(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.corp_id</code>.
     */
    public Long getCorpId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.mis_sale_order_item.occur_at</code>.
     */
    public MisSaleOrderItemRecord setOccurAt(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.occur_at</code>.
     */
    public LocalDateTime getOccurAt() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, BigDecimal, BigDecimal, Long, Long, LocalDateTime, String, LocalDateTime, String, Long, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, Long, BigDecimal, BigDecimal, Long, Long, LocalDateTime, String, LocalDateTime, String, Long, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.ID;
    }

    @Override
    public Field<Long> field2() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.PRODUCT_ID;
    }

    @Override
    public Field<BigDecimal> field3() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.QUANTITY;
    }

    @Override
    public Field<BigDecimal> field4() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.PRICE;
    }

    @Override
    public Field<Long> field5() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.CUSTOMER_ID;
    }

    @Override
    public Field<Long> field6() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.SALE_ORDER_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.CREATED_AT;
    }

    @Override
    public Field<String> field8() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.UPDTED_AT;
    }

    @Override
    public Field<String> field10() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.UPDATED_BY;
    }

    @Override
    public Field<Long> field11() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.CORP_ID;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return MisSaleOrderItem.MIS_SALE_ORDER_ITEM.OCCUR_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getProductId();
    }

    @Override
    public BigDecimal component3() {
        return getQuantity();
    }

    @Override
    public BigDecimal component4() {
        return getPrice();
    }

    @Override
    public Long component5() {
        return getCustomerId();
    }

    @Override
    public Long component6() {
        return getSaleOrderId();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public String component8() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdtedAt();
    }

    @Override
    public String component10() {
        return getUpdatedBy();
    }

    @Override
    public Long component11() {
        return getCorpId();
    }

    @Override
    public LocalDateTime component12() {
        return getOccurAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getProductId();
    }

    @Override
    public BigDecimal value3() {
        return getQuantity();
    }

    @Override
    public BigDecimal value4() {
        return getPrice();
    }

    @Override
    public Long value5() {
        return getCustomerId();
    }

    @Override
    public Long value6() {
        return getSaleOrderId();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public String value8() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdtedAt();
    }

    @Override
    public String value10() {
        return getUpdatedBy();
    }

    @Override
    public Long value11() {
        return getCorpId();
    }

    @Override
    public LocalDateTime value12() {
        return getOccurAt();
    }

    @Override
    public MisSaleOrderItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value2(Long value) {
        setProductId(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value3(BigDecimal value) {
        setQuantity(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value4(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value5(Long value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value6(Long value) {
        setSaleOrderId(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value8(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value9(LocalDateTime value) {
        setUpdtedAt(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value10(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value11(Long value) {
        setCorpId(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord value12(LocalDateTime value) {
        setOccurAt(value);
        return this;
    }

    @Override
    public MisSaleOrderItemRecord values(Long value1, Long value2, BigDecimal value3, BigDecimal value4, Long value5, Long value6, LocalDateTime value7, String value8, LocalDateTime value9, String value10, Long value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MisSaleOrderItemRecord
     */
    public MisSaleOrderItemRecord() {
        super(MisSaleOrderItem.MIS_SALE_ORDER_ITEM);
    }

    /**
     * Create a detached, initialised MisSaleOrderItemRecord
     */
    public MisSaleOrderItemRecord(Long id, Long productId, BigDecimal quantity, BigDecimal price, Long customerId, Long saleOrderId, LocalDateTime createdAt, String createdBy, LocalDateTime updtedAt, String updatedBy, Long corpId, LocalDateTime occurAt) {
        super(MisSaleOrderItem.MIS_SALE_ORDER_ITEM);

        setId(id);
        setProductId(productId);
        setQuantity(quantity);
        setPrice(price);
        setCustomerId(customerId);
        setSaleOrderId(saleOrderId);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdtedAt(updtedAt);
        setUpdatedBy(updatedBy);
        setCorpId(corpId);
        setOccurAt(occurAt);
    }

    /**
     * Create a detached, initialised MisSaleOrderItemRecord
     */
    public MisSaleOrderItemRecord(com.agri.mis.db.tables.pojos.MisSaleOrderItem value) {
        super(MisSaleOrderItem.MIS_SALE_ORDER_ITEM);

        if (value != null) {
            setId(value.getId());
            setProductId(value.getProductId());
            setQuantity(value.getQuantity());
            setPrice(value.getPrice());
            setCustomerId(value.getCustomerId());
            setSaleOrderId(value.getSaleOrderId());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdtedAt(value.getUpdtedAt());
            setUpdatedBy(value.getUpdatedBy());
            setCorpId(value.getCorpId());
            setOccurAt(value.getOccurAt());
        }
    }
}
