/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.records;


import com.agri.mis.db.tables.MisStockPlaceItem;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MisStockPlaceItemRecord extends UpdatableRecordImpl<MisStockPlaceItemRecord> implements Record6<Long, Long, Long, BigDecimal, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mis_stock_place_item.id</code>.
     */
    public MisStockPlaceItemRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_stock_place_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mis_stock_place_item.stock_place_id</code>.
     */
    public MisStockPlaceItemRecord setStockPlaceId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_stock_place_item.stock_place_id</code>.
     */
    public Long getStockPlaceId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mis_stock_place_item.product_id</code>.
     */
    public MisStockPlaceItemRecord setProductId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_stock_place_item.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.mis_stock_place_item.quantity</code>.
     */
    public MisStockPlaceItemRecord setQuantity(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_stock_place_item.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.mis_stock_place_item.box_code</code>.
     */
    public MisStockPlaceItemRecord setBoxCode(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_stock_place_item.box_code</code>.
     */
    public String getBoxCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mis_stock_place_item.product_code</code>.
     */
    public MisStockPlaceItemRecord setProductCode(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.mis_stock_place_item.product_code</code>.
     */
    public String getProductCode() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, BigDecimal, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, BigDecimal, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MisStockPlaceItem.MIS_STOCK_PLACE_ITEM.ID;
    }

    @Override
    public Field<Long> field2() {
        return MisStockPlaceItem.MIS_STOCK_PLACE_ITEM.STOCK_PLACE_ID;
    }

    @Override
    public Field<Long> field3() {
        return MisStockPlaceItem.MIS_STOCK_PLACE_ITEM.PRODUCT_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return MisStockPlaceItem.MIS_STOCK_PLACE_ITEM.QUANTITY;
    }

    @Override
    public Field<String> field5() {
        return MisStockPlaceItem.MIS_STOCK_PLACE_ITEM.BOX_CODE;
    }

    @Override
    public Field<String> field6() {
        return MisStockPlaceItem.MIS_STOCK_PLACE_ITEM.PRODUCT_CODE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getStockPlaceId();
    }

    @Override
    public Long component3() {
        return getProductId();
    }

    @Override
    public BigDecimal component4() {
        return getQuantity();
    }

    @Override
    public String component5() {
        return getBoxCode();
    }

    @Override
    public String component6() {
        return getProductCode();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getStockPlaceId();
    }

    @Override
    public Long value3() {
        return getProductId();
    }

    @Override
    public BigDecimal value4() {
        return getQuantity();
    }

    @Override
    public String value5() {
        return getBoxCode();
    }

    @Override
    public String value6() {
        return getProductCode();
    }

    @Override
    public MisStockPlaceItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MisStockPlaceItemRecord value2(Long value) {
        setStockPlaceId(value);
        return this;
    }

    @Override
    public MisStockPlaceItemRecord value3(Long value) {
        setProductId(value);
        return this;
    }

    @Override
    public MisStockPlaceItemRecord value4(BigDecimal value) {
        setQuantity(value);
        return this;
    }

    @Override
    public MisStockPlaceItemRecord value5(String value) {
        setBoxCode(value);
        return this;
    }

    @Override
    public MisStockPlaceItemRecord value6(String value) {
        setProductCode(value);
        return this;
    }

    @Override
    public MisStockPlaceItemRecord values(Long value1, Long value2, Long value3, BigDecimal value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MisStockPlaceItemRecord
     */
    public MisStockPlaceItemRecord() {
        super(MisStockPlaceItem.MIS_STOCK_PLACE_ITEM);
    }

    /**
     * Create a detached, initialised MisStockPlaceItemRecord
     */
    public MisStockPlaceItemRecord(Long id, Long stockPlaceId, Long productId, BigDecimal quantity, String boxCode, String productCode) {
        super(MisStockPlaceItem.MIS_STOCK_PLACE_ITEM);

        setId(id);
        setStockPlaceId(stockPlaceId);
        setProductId(productId);
        setQuantity(quantity);
        setBoxCode(boxCode);
        setProductCode(productCode);
    }

    /**
     * Create a detached, initialised MisStockPlaceItemRecord
     */
    public MisStockPlaceItemRecord(com.agri.mis.db.tables.pojos.MisStockPlaceItem value) {
        super(MisStockPlaceItem.MIS_STOCK_PLACE_ITEM);

        if (value != null) {
            setId(value.getId());
            setStockPlaceId(value.getStockPlaceId());
            setProductId(value.getProductId());
            setQuantity(value.getQuantity());
            setBoxCode(value.getBoxCode());
            setProductCode(value.getProductCode());
        }
    }
}
