/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchTeam implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long batchId;
    private Long userId;
    private Boolean isManager;
    private LocalDateTime createdAt;

    public BatchTeam() {}

    public BatchTeam(BatchTeam value) {
        this.id = value.id;
        this.batchId = value.batchId;
        this.userId = value.userId;
        this.isManager = value.isManager;
        this.createdAt = value.createdAt;
    }

    public BatchTeam(
        Long id,
        Long batchId,
        Long userId,
        Boolean isManager,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.batchId = batchId;
        this.userId = userId;
        this.isManager = isManager;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.batch_team.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.batch_team.id</code>.
     */
    public BatchTeam setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.batch_team.batch_id</code>.
     */
    public Long getBatchId() {
        return this.batchId;
    }

    /**
     * Setter for <code>public.batch_team.batch_id</code>.
     */
    public BatchTeam setBatchId(Long batchId) {
        this.batchId = batchId;
        return this;
    }

    /**
     * Getter for <code>public.batch_team.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.batch_team.user_id</code>.
     */
    public BatchTeam setUserId(Long userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.batch_team.is_manager</code>.
     */
    public Boolean getIsManager() {
        return this.isManager;
    }

    /**
     * Setter for <code>public.batch_team.is_manager</code>.
     */
    public BatchTeam setIsManager(Boolean isManager) {
        this.isManager = isManager;
        return this;
    }

    /**
     * Getter for <code>public.batch_team.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.batch_team.created_at</code>.
     */
    public BatchTeam setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BatchTeam other = (BatchTeam) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.batchId == null) {
            if (other.batchId != null)
                return false;
        }
        else if (!this.batchId.equals(other.batchId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.isManager == null) {
            if (other.isManager != null)
                return false;
        }
        else if (!this.isManager.equals(other.isManager))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.batchId == null) ? 0 : this.batchId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.isManager == null) ? 0 : this.isManager.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BatchTeam (");

        sb.append(id);
        sb.append(", ").append(batchId);
        sb.append(", ").append(userId);
        sb.append(", ").append(isManager);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
