/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchProduct implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String code;
    private Long productId;
    private LocalDate startAt;
    private LocalDate endAt;
    private Integer days;
    private Double productionEstimated;
    private Double productionReal;
    private BigDecimal investEstimated;
    private BigDecimal investReal;
    private Long corpId;
    private String calcUnit;
    private Long parkId;
    private Long createdUserId;
    private String createdBy;
    private LocalDateTime createdAt;
    private String description;
    private Double quantity;
    private Integer status;

    public BatchProduct() {}

    public BatchProduct(BatchProduct value) {
        this.id = value.id;
        this.name = value.name;
        this.code = value.code;
        this.productId = value.productId;
        this.startAt = value.startAt;
        this.endAt = value.endAt;
        this.days = value.days;
        this.productionEstimated = value.productionEstimated;
        this.productionReal = value.productionReal;
        this.investEstimated = value.investEstimated;
        this.investReal = value.investReal;
        this.corpId = value.corpId;
        this.calcUnit = value.calcUnit;
        this.parkId = value.parkId;
        this.createdUserId = value.createdUserId;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
        this.description = value.description;
        this.quantity = value.quantity;
        this.status = value.status;
    }

    public BatchProduct(
        Long id,
        String name,
        String code,
        Long productId,
        LocalDate startAt,
        LocalDate endAt,
        Integer days,
        Double productionEstimated,
        Double productionReal,
        BigDecimal investEstimated,
        BigDecimal investReal,
        Long corpId,
        String calcUnit,
        Long parkId,
        Long createdUserId,
        String createdBy,
        LocalDateTime createdAt,
        String description,
        Double quantity,
        Integer status
    ) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.productId = productId;
        this.startAt = startAt;
        this.endAt = endAt;
        this.days = days;
        this.productionEstimated = productionEstimated;
        this.productionReal = productionReal;
        this.investEstimated = investEstimated;
        this.investReal = investReal;
        this.corpId = corpId;
        this.calcUnit = calcUnit;
        this.parkId = parkId;
        this.createdUserId = createdUserId;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.description = description;
        this.quantity = quantity;
        this.status = status;
    }

    /**
     * Getter for <code>public.batch_product.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.batch_product.id</code>.
     */
    public BatchProduct setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.batch_product.name</code>.
     */
    public BatchProduct setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>public.batch_product.code</code>.
     */
    public BatchProduct setCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.product_id</code>.
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>public.batch_product.product_id</code>.
     */
    public BatchProduct setProductId(Long productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.start_at</code>.
     */
    public LocalDate getStartAt() {
        return this.startAt;
    }

    /**
     * Setter for <code>public.batch_product.start_at</code>.
     */
    public BatchProduct setStartAt(LocalDate startAt) {
        this.startAt = startAt;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.end_at</code>.
     */
    public LocalDate getEndAt() {
        return this.endAt;
    }

    /**
     * Setter for <code>public.batch_product.end_at</code>.
     */
    public BatchProduct setEndAt(LocalDate endAt) {
        this.endAt = endAt;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.days</code>.
     */
    public Integer getDays() {
        return this.days;
    }

    /**
     * Setter for <code>public.batch_product.days</code>.
     */
    public BatchProduct setDays(Integer days) {
        this.days = days;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.production_estimated</code>.
     */
    public Double getProductionEstimated() {
        return this.productionEstimated;
    }

    /**
     * Setter for <code>public.batch_product.production_estimated</code>.
     */
    public BatchProduct setProductionEstimated(Double productionEstimated) {
        this.productionEstimated = productionEstimated;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.production_real</code>.
     */
    public Double getProductionReal() {
        return this.productionReal;
    }

    /**
     * Setter for <code>public.batch_product.production_real</code>.
     */
    public BatchProduct setProductionReal(Double productionReal) {
        this.productionReal = productionReal;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.invest_estimated</code>.
     */
    public BigDecimal getInvestEstimated() {
        return this.investEstimated;
    }

    /**
     * Setter for <code>public.batch_product.invest_estimated</code>.
     */
    public BatchProduct setInvestEstimated(BigDecimal investEstimated) {
        this.investEstimated = investEstimated;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.invest_real</code>.
     */
    public BigDecimal getInvestReal() {
        return this.investReal;
    }

    /**
     * Setter for <code>public.batch_product.invest_real</code>.
     */
    public BatchProduct setInvestReal(BigDecimal investReal) {
        this.investReal = investReal;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.corp_id</code>.
     */
    public Long getCorpId() {
        return this.corpId;
    }

    /**
     * Setter for <code>public.batch_product.corp_id</code>.
     */
    public BatchProduct setCorpId(Long corpId) {
        this.corpId = corpId;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.calc_unit</code>.
     */
    public String getCalcUnit() {
        return this.calcUnit;
    }

    /**
     * Setter for <code>public.batch_product.calc_unit</code>.
     */
    public BatchProduct setCalcUnit(String calcUnit) {
        this.calcUnit = calcUnit;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.park_id</code>.
     */
    public Long getParkId() {
        return this.parkId;
    }

    /**
     * Setter for <code>public.batch_product.park_id</code>.
     */
    public BatchProduct setParkId(Long parkId) {
        this.parkId = parkId;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.created_user_id</code>.
     */
    public Long getCreatedUserId() {
        return this.createdUserId;
    }

    /**
     * Setter for <code>public.batch_product.created_user_id</code>.
     */
    public BatchProduct setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.batch_product.created_by</code>.
     */
    public BatchProduct setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.batch_product.created_at</code>.
     */
    public BatchProduct setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.batch_product.description</code>.
     */
    public BatchProduct setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.quantity</code>.
     */
    public Double getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>public.batch_product.quantity</code>.
     */
    public BatchProduct setQuantity(Double quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Getter for <code>public.batch_product.status</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.batch_product.status</code>.
     */
    public BatchProduct setStatus(Integer status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BatchProduct other = (BatchProduct) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        if (this.startAt == null) {
            if (other.startAt != null)
                return false;
        }
        else if (!this.startAt.equals(other.startAt))
            return false;
        if (this.endAt == null) {
            if (other.endAt != null)
                return false;
        }
        else if (!this.endAt.equals(other.endAt))
            return false;
        if (this.days == null) {
            if (other.days != null)
                return false;
        }
        else if (!this.days.equals(other.days))
            return false;
        if (this.productionEstimated == null) {
            if (other.productionEstimated != null)
                return false;
        }
        else if (!this.productionEstimated.equals(other.productionEstimated))
            return false;
        if (this.productionReal == null) {
            if (other.productionReal != null)
                return false;
        }
        else if (!this.productionReal.equals(other.productionReal))
            return false;
        if (this.investEstimated == null) {
            if (other.investEstimated != null)
                return false;
        }
        else if (!this.investEstimated.equals(other.investEstimated))
            return false;
        if (this.investReal == null) {
            if (other.investReal != null)
                return false;
        }
        else if (!this.investReal.equals(other.investReal))
            return false;
        if (this.corpId == null) {
            if (other.corpId != null)
                return false;
        }
        else if (!this.corpId.equals(other.corpId))
            return false;
        if (this.calcUnit == null) {
            if (other.calcUnit != null)
                return false;
        }
        else if (!this.calcUnit.equals(other.calcUnit))
            return false;
        if (this.parkId == null) {
            if (other.parkId != null)
                return false;
        }
        else if (!this.parkId.equals(other.parkId))
            return false;
        if (this.createdUserId == null) {
            if (other.createdUserId != null)
                return false;
        }
        else if (!this.createdUserId.equals(other.createdUserId))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!this.quantity.equals(other.quantity))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.startAt == null) ? 0 : this.startAt.hashCode());
        result = prime * result + ((this.endAt == null) ? 0 : this.endAt.hashCode());
        result = prime * result + ((this.days == null) ? 0 : this.days.hashCode());
        result = prime * result + ((this.productionEstimated == null) ? 0 : this.productionEstimated.hashCode());
        result = prime * result + ((this.productionReal == null) ? 0 : this.productionReal.hashCode());
        result = prime * result + ((this.investEstimated == null) ? 0 : this.investEstimated.hashCode());
        result = prime * result + ((this.investReal == null) ? 0 : this.investReal.hashCode());
        result = prime * result + ((this.corpId == null) ? 0 : this.corpId.hashCode());
        result = prime * result + ((this.calcUnit == null) ? 0 : this.calcUnit.hashCode());
        result = prime * result + ((this.parkId == null) ? 0 : this.parkId.hashCode());
        result = prime * result + ((this.createdUserId == null) ? 0 : this.createdUserId.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BatchProduct (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(productId);
        sb.append(", ").append(startAt);
        sb.append(", ").append(endAt);
        sb.append(", ").append(days);
        sb.append(", ").append(productionEstimated);
        sb.append(", ").append(productionReal);
        sb.append(", ").append(investEstimated);
        sb.append(", ").append(investReal);
        sb.append(", ").append(corpId);
        sb.append(", ").append(calcUnit);
        sb.append(", ").append(parkId);
        sb.append(", ").append(createdUserId);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(description);
        sb.append(", ").append(quantity);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
