/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchCycleExpense implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String description;
    private BigDecimal amount;
    private Long corpId;
    private Long batchId;
    private String expenseType;
    private String name;
    private LocalDateTime createdAt;
    private Long createdUserId;
    private String code;
    private String cycleName;
    private Integer status;
    private Integer checkStatus;

    public BatchCycleExpense() {}

    public BatchCycleExpense(BatchCycleExpense value) {
        this.id = value.id;
        this.description = value.description;
        this.amount = value.amount;
        this.corpId = value.corpId;
        this.batchId = value.batchId;
        this.expenseType = value.expenseType;
        this.name = value.name;
        this.createdAt = value.createdAt;
        this.createdUserId = value.createdUserId;
        this.code = value.code;
        this.cycleName = value.cycleName;
        this.status = value.status;
        this.checkStatus = value.checkStatus;
    }

    public BatchCycleExpense(
        Long id,
        String description,
        BigDecimal amount,
        Long corpId,
        Long batchId,
        String expenseType,
        String name,
        LocalDateTime createdAt,
        Long createdUserId,
        String code,
        String cycleName,
        Integer status,
        Integer checkStatus
    ) {
        this.id = id;
        this.description = description;
        this.amount = amount;
        this.corpId = corpId;
        this.batchId = batchId;
        this.expenseType = expenseType;
        this.name = name;
        this.createdAt = createdAt;
        this.createdUserId = createdUserId;
        this.code = code;
        this.cycleName = cycleName;
        this.status = status;
        this.checkStatus = checkStatus;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.id</code>.
     */
    public BatchCycleExpense setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.description</code>.
     */
    public BatchCycleExpense setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.amount</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.amount</code>.
     */
    public BatchCycleExpense setAmount(BigDecimal amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.corp_id</code>.
     */
    public Long getCorpId() {
        return this.corpId;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.corp_id</code>.
     */
    public BatchCycleExpense setCorpId(Long corpId) {
        this.corpId = corpId;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.batch_id</code>.
     */
    public Long getBatchId() {
        return this.batchId;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.batch_id</code>.
     */
    public BatchCycleExpense setBatchId(Long batchId) {
        this.batchId = batchId;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.expense_type</code>.
     */
    public String getExpenseType() {
        return this.expenseType;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.expense_type</code>.
     */
    public BatchCycleExpense setExpenseType(String expenseType) {
        this.expenseType = expenseType;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.name</code>.
     */
    public BatchCycleExpense setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.created_at</code>.
     */
    public BatchCycleExpense setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.created_user_id</code>.
     */
    public Long getCreatedUserId() {
        return this.createdUserId;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.created_user_id</code>.
     */
    public BatchCycleExpense setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.code</code>.
     */
    public BatchCycleExpense setCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.cycle_name</code>.
     */
    public String getCycleName() {
        return this.cycleName;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.cycle_name</code>.
     */
    public BatchCycleExpense setCycleName(String cycleName) {
        this.cycleName = cycleName;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.status</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.status</code>.
     */
    public BatchCycleExpense setStatus(Integer status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.batch_cycle_expense.check_status</code>.
     */
    public Integer getCheckStatus() {
        return this.checkStatus;
    }

    /**
     * Setter for <code>public.batch_cycle_expense.check_status</code>.
     */
    public BatchCycleExpense setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BatchCycleExpense other = (BatchCycleExpense) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.corpId == null) {
            if (other.corpId != null)
                return false;
        }
        else if (!this.corpId.equals(other.corpId))
            return false;
        if (this.batchId == null) {
            if (other.batchId != null)
                return false;
        }
        else if (!this.batchId.equals(other.batchId))
            return false;
        if (this.expenseType == null) {
            if (other.expenseType != null)
                return false;
        }
        else if (!this.expenseType.equals(other.expenseType))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.createdUserId == null) {
            if (other.createdUserId != null)
                return false;
        }
        else if (!this.createdUserId.equals(other.createdUserId))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.cycleName == null) {
            if (other.cycleName != null)
                return false;
        }
        else if (!this.cycleName.equals(other.cycleName))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.checkStatus == null) {
            if (other.checkStatus != null)
                return false;
        }
        else if (!this.checkStatus.equals(other.checkStatus))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.corpId == null) ? 0 : this.corpId.hashCode());
        result = prime * result + ((this.batchId == null) ? 0 : this.batchId.hashCode());
        result = prime * result + ((this.expenseType == null) ? 0 : this.expenseType.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.createdUserId == null) ? 0 : this.createdUserId.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.cycleName == null) ? 0 : this.cycleName.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.checkStatus == null) ? 0 : this.checkStatus.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BatchCycleExpense (");

        sb.append(id);
        sb.append(", ").append(description);
        sb.append(", ").append(amount);
        sb.append(", ").append(corpId);
        sb.append(", ").append(batchId);
        sb.append(", ").append(expenseType);
        sb.append(", ").append(name);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdUserId);
        sb.append(", ").append(code);
        sb.append(", ").append(cycleName);
        sb.append(", ").append(status);
        sb.append(", ").append(checkStatus);

        sb.append(")");
        return sb.toString();
    }
}
