/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchRisk implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long productId;
    private Long batchId;
    private String cycleName;
    private String riskCategory;
    private String discription;
    private String solution;
    private BigDecimal feeAmount;
    private Long createdUserId;
    private String createdBy;
    private LocalDate occurDate;
    private LocalDateTime createdAt;
    private Long corpId;

    public BatchRisk() {}

    public BatchRisk(BatchRisk value) {
        this.id = value.id;
        this.productId = value.productId;
        this.batchId = value.batchId;
        this.cycleName = value.cycleName;
        this.riskCategory = value.riskCategory;
        this.discription = value.discription;
        this.solution = value.solution;
        this.feeAmount = value.feeAmount;
        this.createdUserId = value.createdUserId;
        this.createdBy = value.createdBy;
        this.occurDate = value.occurDate;
        this.createdAt = value.createdAt;
        this.corpId = value.corpId;
    }

    public BatchRisk(
        Long id,
        Long productId,
        Long batchId,
        String cycleName,
        String riskCategory,
        String discription,
        String solution,
        BigDecimal feeAmount,
        Long createdUserId,
        String createdBy,
        LocalDate occurDate,
        LocalDateTime createdAt,
        Long corpId
    ) {
        this.id = id;
        this.productId = productId;
        this.batchId = batchId;
        this.cycleName = cycleName;
        this.riskCategory = riskCategory;
        this.discription = discription;
        this.solution = solution;
        this.feeAmount = feeAmount;
        this.createdUserId = createdUserId;
        this.createdBy = createdBy;
        this.occurDate = occurDate;
        this.createdAt = createdAt;
        this.corpId = corpId;
    }

    /**
     * Getter for <code>public.batch_risk.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.batch_risk.id</code>.
     */
    public BatchRisk setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.product_id</code>.
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>public.batch_risk.product_id</code>.
     */
    public BatchRisk setProductId(Long productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.batch_id</code>.
     */
    public Long getBatchId() {
        return this.batchId;
    }

    /**
     * Setter for <code>public.batch_risk.batch_id</code>.
     */
    public BatchRisk setBatchId(Long batchId) {
        this.batchId = batchId;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.cycle_name</code>.
     */
    public String getCycleName() {
        return this.cycleName;
    }

    /**
     * Setter for <code>public.batch_risk.cycle_name</code>.
     */
    public BatchRisk setCycleName(String cycleName) {
        this.cycleName = cycleName;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.risk_category</code>.
     */
    public String getRiskCategory() {
        return this.riskCategory;
    }

    /**
     * Setter for <code>public.batch_risk.risk_category</code>.
     */
    public BatchRisk setRiskCategory(String riskCategory) {
        this.riskCategory = riskCategory;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.discription</code>.
     */
    public String getDiscription() {
        return this.discription;
    }

    /**
     * Setter for <code>public.batch_risk.discription</code>.
     */
    public BatchRisk setDiscription(String discription) {
        this.discription = discription;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.solution</code>.
     */
    public String getSolution() {
        return this.solution;
    }

    /**
     * Setter for <code>public.batch_risk.solution</code>.
     */
    public BatchRisk setSolution(String solution) {
        this.solution = solution;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.fee_amount</code>.
     */
    public BigDecimal getFeeAmount() {
        return this.feeAmount;
    }

    /**
     * Setter for <code>public.batch_risk.fee_amount</code>.
     */
    public BatchRisk setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.created_user_id</code>.
     */
    public Long getCreatedUserId() {
        return this.createdUserId;
    }

    /**
     * Setter for <code>public.batch_risk.created_user_id</code>.
     */
    public BatchRisk setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.batch_risk.created_by</code>.
     */
    public BatchRisk setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.occur_date</code>.
     */
    public LocalDate getOccurDate() {
        return this.occurDate;
    }

    /**
     * Setter for <code>public.batch_risk.occur_date</code>.
     */
    public BatchRisk setOccurDate(LocalDate occurDate) {
        this.occurDate = occurDate;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.batch_risk.created_at</code>.
     */
    public BatchRisk setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.batch_risk.corp_id</code>.
     */
    public Long getCorpId() {
        return this.corpId;
    }

    /**
     * Setter for <code>public.batch_risk.corp_id</code>.
     */
    public BatchRisk setCorpId(Long corpId) {
        this.corpId = corpId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BatchRisk other = (BatchRisk) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        if (this.batchId == null) {
            if (other.batchId != null)
                return false;
        }
        else if (!this.batchId.equals(other.batchId))
            return false;
        if (this.cycleName == null) {
            if (other.cycleName != null)
                return false;
        }
        else if (!this.cycleName.equals(other.cycleName))
            return false;
        if (this.riskCategory == null) {
            if (other.riskCategory != null)
                return false;
        }
        else if (!this.riskCategory.equals(other.riskCategory))
            return false;
        if (this.discription == null) {
            if (other.discription != null)
                return false;
        }
        else if (!this.discription.equals(other.discription))
            return false;
        if (this.solution == null) {
            if (other.solution != null)
                return false;
        }
        else if (!this.solution.equals(other.solution))
            return false;
        if (this.feeAmount == null) {
            if (other.feeAmount != null)
                return false;
        }
        else if (!this.feeAmount.equals(other.feeAmount))
            return false;
        if (this.createdUserId == null) {
            if (other.createdUserId != null)
                return false;
        }
        else if (!this.createdUserId.equals(other.createdUserId))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.occurDate == null) {
            if (other.occurDate != null)
                return false;
        }
        else if (!this.occurDate.equals(other.occurDate))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.corpId == null) {
            if (other.corpId != null)
                return false;
        }
        else if (!this.corpId.equals(other.corpId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.batchId == null) ? 0 : this.batchId.hashCode());
        result = prime * result + ((this.cycleName == null) ? 0 : this.cycleName.hashCode());
        result = prime * result + ((this.riskCategory == null) ? 0 : this.riskCategory.hashCode());
        result = prime * result + ((this.discription == null) ? 0 : this.discription.hashCode());
        result = prime * result + ((this.solution == null) ? 0 : this.solution.hashCode());
        result = prime * result + ((this.feeAmount == null) ? 0 : this.feeAmount.hashCode());
        result = prime * result + ((this.createdUserId == null) ? 0 : this.createdUserId.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.occurDate == null) ? 0 : this.occurDate.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.corpId == null) ? 0 : this.corpId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BatchRisk (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(batchId);
        sb.append(", ").append(cycleName);
        sb.append(", ").append(riskCategory);
        sb.append(", ").append(discription);
        sb.append(", ").append(solution);
        sb.append(", ").append(feeAmount);
        sb.append(", ").append(createdUserId);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(occurDate);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(corpId);

        sb.append(")");
        return sb.toString();
    }
}
