/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorpManagerDepart implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long managerId;
    private Long departId;

    public CorpManagerDepart() {}

    public CorpManagerDepart(CorpManagerDepart value) {
        this.id = value.id;
        this.managerId = value.managerId;
        this.departId = value.departId;
    }

    public CorpManagerDepart(
        Long id,
        Long managerId,
        Long departId
    ) {
        this.id = id;
        this.managerId = managerId;
        this.departId = departId;
    }

    /**
     * Getter for <code>public.corp_manager_depart.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.corp_manager_depart.id</code>.
     */
    public CorpManagerDepart setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.corp_manager_depart.manager_id</code>.
     */
    public Long getManagerId() {
        return this.managerId;
    }

    /**
     * Setter for <code>public.corp_manager_depart.manager_id</code>.
     */
    public CorpManagerDepart setManagerId(Long managerId) {
        this.managerId = managerId;
        return this;
    }

    /**
     * Getter for <code>public.corp_manager_depart.depart_id</code>.
     */
    public Long getDepartId() {
        return this.departId;
    }

    /**
     * Setter for <code>public.corp_manager_depart.depart_id</code>.
     */
    public CorpManagerDepart setDepartId(Long departId) {
        this.departId = departId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CorpManagerDepart other = (CorpManagerDepart) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.managerId == null) {
            if (other.managerId != null)
                return false;
        }
        else if (!this.managerId.equals(other.managerId))
            return false;
        if (this.departId == null) {
            if (other.departId != null)
                return false;
        }
        else if (!this.departId.equals(other.departId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.managerId == null) ? 0 : this.managerId.hashCode());
        result = prime * result + ((this.departId == null) ? 0 : this.departId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CorpManagerDepart (");

        sb.append(id);
        sb.append(", ").append(managerId);
        sb.append(", ").append(departId);

        sb.append(")");
        return sb.toString();
    }
}
