/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorpRoleMenu implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long roleId;
    private Long menuId;
    private String actions;

    public CorpRoleMenu() {}

    public CorpRoleMenu(CorpRoleMenu value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.menuId = value.menuId;
        this.actions = value.actions;
    }

    public CorpRoleMenu(
        Long id,
        Long roleId,
        Long menuId,
        String actions
    ) {
        this.id = id;
        this.roleId = roleId;
        this.menuId = menuId;
        this.actions = actions;
    }

    /**
     * Getter for <code>public.corp_role_menu.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.corp_role_menu.id</code>.
     */
    public CorpRoleMenu setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.corp_role_menu.role_id</code>.
     */
    public Long getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>public.corp_role_menu.role_id</code>.
     */
    public CorpRoleMenu setRoleId(Long roleId) {
        this.roleId = roleId;
        return this;
    }

    /**
     * Getter for <code>public.corp_role_menu.menu_id</code>.
     */
    public Long getMenuId() {
        return this.menuId;
    }

    /**
     * Setter for <code>public.corp_role_menu.menu_id</code>.
     */
    public CorpRoleMenu setMenuId(Long menuId) {
        this.menuId = menuId;
        return this;
    }

    /**
     * Getter for <code>public.corp_role_menu.actions</code>.
     */
    public String getActions() {
        return this.actions;
    }

    /**
     * Setter for <code>public.corp_role_menu.actions</code>.
     */
    public CorpRoleMenu setActions(String actions) {
        this.actions = actions;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CorpRoleMenu other = (CorpRoleMenu) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!this.roleId.equals(other.roleId))
            return false;
        if (this.menuId == null) {
            if (other.menuId != null)
                return false;
        }
        else if (!this.menuId.equals(other.menuId))
            return false;
        if (this.actions == null) {
            if (other.actions != null)
                return false;
        }
        else if (!this.actions.equals(other.actions))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        result = prime * result + ((this.menuId == null) ? 0 : this.menuId.hashCode());
        result = prime * result + ((this.actions == null) ? 0 : this.actions.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CorpRoleMenu (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(menuId);
        sb.append(", ").append(actions);

        sb.append(")");
        return sb.toString();
    }
}
