/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerTrace implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long customerId;
    private String description;
    private String title;
    private String linkName;
    private String linkMobile;
    private Long createdBy;
    private LocalDateTime createdAt;
    private Long corpId;
    private LocalDateTime occurAt;
    private Long createdUserId;

    public CustomerTrace() {}

    public CustomerTrace(CustomerTrace value) {
        this.id = value.id;
        this.customerId = value.customerId;
        this.description = value.description;
        this.title = value.title;
        this.linkName = value.linkName;
        this.linkMobile = value.linkMobile;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
        this.corpId = value.corpId;
        this.occurAt = value.occurAt;
        this.createdUserId = value.createdUserId;
    }

    public CustomerTrace(
        Long id,
        Long customerId,
        String description,
        String title,
        String linkName,
        String linkMobile,
        Long createdBy,
        LocalDateTime createdAt,
        Long corpId,
        LocalDateTime occurAt,
        Long createdUserId
    ) {
        this.id = id;
        this.customerId = customerId;
        this.description = description;
        this.title = title;
        this.linkName = linkName;
        this.linkMobile = linkMobile;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.corpId = corpId;
        this.occurAt = occurAt;
        this.createdUserId = createdUserId;
    }

    /**
     * Getter for <code>public.customer_trace.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.customer_trace.id</code>.
     */
    public CustomerTrace setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.customer_trace.customer_id</code>.
     */
    public Long getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>public.customer_trace.customer_id</code>.
     */
    public CustomerTrace setCustomerId(Long customerId) {
        this.customerId = customerId;
        return this;
    }

    /**
     * Getter for <code>public.customer_trace.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.customer_trace.description</code>.
     */
    public CustomerTrace setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>public.customer_trace.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.customer_trace.title</code>.
     */
    public CustomerTrace setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>public.customer_trace.link_name</code>.
     */
    public String getLinkName() {
        return this.linkName;
    }

    /**
     * Setter for <code>public.customer_trace.link_name</code>.
     */
    public CustomerTrace setLinkName(String linkName) {
        this.linkName = linkName;
        return this;
    }

    /**
     * Getter for <code>public.customer_trace.link_mobile</code>.
     */
    public String getLinkMobile() {
        return this.linkMobile;
    }

    /**
     * Setter for <code>public.customer_trace.link_mobile</code>.
     */
    public CustomerTrace setLinkMobile(String linkMobile) {
        this.linkMobile = linkMobile;
        return this;
    }

    /**
     * Getter for <code>public.customer_trace.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.customer_trace.created_by</code>.
     */
    public CustomerTrace setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.customer_trace.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.customer_trace.created_at</code>.
     */
    public CustomerTrace setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.customer_trace.corp_id</code>.
     */
    public Long getCorpId() {
        return this.corpId;
    }

    /**
     * Setter for <code>public.customer_trace.corp_id</code>.
     */
    public CustomerTrace setCorpId(Long corpId) {
        this.corpId = corpId;
        return this;
    }

    /**
     * Getter for <code>public.customer_trace.occur_at</code>.
     */
    public LocalDateTime getOccurAt() {
        return this.occurAt;
    }

    /**
     * Setter for <code>public.customer_trace.occur_at</code>.
     */
    public CustomerTrace setOccurAt(LocalDateTime occurAt) {
        this.occurAt = occurAt;
        return this;
    }

    /**
     * Getter for <code>public.customer_trace.created_user_id</code>.
     */
    public Long getCreatedUserId() {
        return this.createdUserId;
    }

    /**
     * Setter for <code>public.customer_trace.created_user_id</code>.
     */
    public CustomerTrace setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CustomerTrace other = (CustomerTrace) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.customerId == null) {
            if (other.customerId != null)
                return false;
        }
        else if (!this.customerId.equals(other.customerId))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.linkName == null) {
            if (other.linkName != null)
                return false;
        }
        else if (!this.linkName.equals(other.linkName))
            return false;
        if (this.linkMobile == null) {
            if (other.linkMobile != null)
                return false;
        }
        else if (!this.linkMobile.equals(other.linkMobile))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.corpId == null) {
            if (other.corpId != null)
                return false;
        }
        else if (!this.corpId.equals(other.corpId))
            return false;
        if (this.occurAt == null) {
            if (other.occurAt != null)
                return false;
        }
        else if (!this.occurAt.equals(other.occurAt))
            return false;
        if (this.createdUserId == null) {
            if (other.createdUserId != null)
                return false;
        }
        else if (!this.createdUserId.equals(other.createdUserId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.linkName == null) ? 0 : this.linkName.hashCode());
        result = prime * result + ((this.linkMobile == null) ? 0 : this.linkMobile.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.corpId == null) ? 0 : this.corpId.hashCode());
        result = prime * result + ((this.occurAt == null) ? 0 : this.occurAt.hashCode());
        result = prime * result + ((this.createdUserId == null) ? 0 : this.createdUserId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomerTrace (");

        sb.append(id);
        sb.append(", ").append(customerId);
        sb.append(", ").append(description);
        sb.append(", ").append(title);
        sb.append(", ").append(linkName);
        sb.append(", ").append(linkMobile);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(corpId);
        sb.append(", ").append(occurAt);
        sb.append(", ").append(createdUserId);

        sb.append(")");
        return sb.toString();
    }
}
