/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarkCategory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String imageUrl;
    private Long parentId;

    public MarkCategory() {}

    public MarkCategory(MarkCategory value) {
        this.id = value.id;
        this.name = value.name;
        this.imageUrl = value.imageUrl;
        this.parentId = value.parentId;
    }

    public MarkCategory(
        Long id,
        String name,
        String imageUrl,
        Long parentId
    ) {
        this.id = id;
        this.name = name;
        this.imageUrl = imageUrl;
        this.parentId = parentId;
    }

    /**
     * Getter for <code>public.mark_category.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.mark_category.id</code>.
     */
    public MarkCategory setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.mark_category.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.mark_category.name</code>.
     */
    public MarkCategory setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.mark_category.image_url</code>.
     */
    public String getImageUrl() {
        return this.imageUrl;
    }

    /**
     * Setter for <code>public.mark_category.image_url</code>.
     */
    public MarkCategory setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
        return this;
    }

    /**
     * Getter for <code>public.mark_category.parent_id</code>.
     */
    public Long getParentId() {
        return this.parentId;
    }

    /**
     * Setter for <code>public.mark_category.parent_id</code>.
     */
    public MarkCategory setParentId(Long parentId) {
        this.parentId = parentId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MarkCategory other = (MarkCategory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.imageUrl == null) {
            if (other.imageUrl != null)
                return false;
        }
        else if (!this.imageUrl.equals(other.imageUrl))
            return false;
        if (this.parentId == null) {
            if (other.parentId != null)
                return false;
        }
        else if (!this.parentId.equals(other.parentId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.imageUrl == null) ? 0 : this.imageUrl.hashCode());
        result = prime * result + ((this.parentId == null) ? 0 : this.parentId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MarkCategory (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(imageUrl);
        sb.append(", ").append(parentId);

        sb.append(")");
        return sb.toString();
    }
}
