/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MisSaleOrderItem implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long productId;
    private BigDecimal quantity;
    private BigDecimal price;
    private Long customerId;
    private Long saleOrderId;
    private LocalDateTime createdAt;
    private String createdBy;
    private LocalDateTime updtedAt;
    private String updatedBy;
    private Long corpId;
    private LocalDateTime occurAt;

    public MisSaleOrderItem() {}

    public MisSaleOrderItem(MisSaleOrderItem value) {
        this.id = value.id;
        this.productId = value.productId;
        this.quantity = value.quantity;
        this.price = value.price;
        this.customerId = value.customerId;
        this.saleOrderId = value.saleOrderId;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
        this.updtedAt = value.updtedAt;
        this.updatedBy = value.updatedBy;
        this.corpId = value.corpId;
        this.occurAt = value.occurAt;
    }

    public MisSaleOrderItem(
        Long id,
        Long productId,
        BigDecimal quantity,
        BigDecimal price,
        Long customerId,
        Long saleOrderId,
        LocalDateTime createdAt,
        String createdBy,
        LocalDateTime updtedAt,
        String updatedBy,
        Long corpId,
        LocalDateTime occurAt
    ) {
        this.id = id;
        this.productId = productId;
        this.quantity = quantity;
        this.price = price;
        this.customerId = customerId;
        this.saleOrderId = saleOrderId;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updtedAt = updtedAt;
        this.updatedBy = updatedBy;
        this.corpId = corpId;
        this.occurAt = occurAt;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.id</code>.
     */
    public MisSaleOrderItem setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.product_id</code>.
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.product_id</code>.
     */
    public MisSaleOrderItem setProductId(Long productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.quantity</code>.
     */
    public MisSaleOrderItem setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.price</code>.
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.price</code>.
     */
    public MisSaleOrderItem setPrice(BigDecimal price) {
        this.price = price;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.customer_id</code>.
     */
    public Long getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.customer_id</code>.
     */
    public MisSaleOrderItem setCustomerId(Long customerId) {
        this.customerId = customerId;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.sale_order_id</code>.
     */
    public Long getSaleOrderId() {
        return this.saleOrderId;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.sale_order_id</code>.
     */
    public MisSaleOrderItem setSaleOrderId(Long saleOrderId) {
        this.saleOrderId = saleOrderId;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.created_at</code>.
     */
    public MisSaleOrderItem setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.created_by</code>.
     */
    public MisSaleOrderItem setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.updted_at</code>.
     */
    public LocalDateTime getUpdtedAt() {
        return this.updtedAt;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.updted_at</code>.
     */
    public MisSaleOrderItem setUpdtedAt(LocalDateTime updtedAt) {
        this.updtedAt = updtedAt;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.updated_by</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.updated_by</code>.
     */
    public MisSaleOrderItem setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.corp_id</code>.
     */
    public Long getCorpId() {
        return this.corpId;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.corp_id</code>.
     */
    public MisSaleOrderItem setCorpId(Long corpId) {
        this.corpId = corpId;
        return this;
    }

    /**
     * Getter for <code>public.mis_sale_order_item.occur_at</code>.
     */
    public LocalDateTime getOccurAt() {
        return this.occurAt;
    }

    /**
     * Setter for <code>public.mis_sale_order_item.occur_at</code>.
     */
    public MisSaleOrderItem setOccurAt(LocalDateTime occurAt) {
        this.occurAt = occurAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MisSaleOrderItem other = (MisSaleOrderItem) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        if (this.quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!this.quantity.equals(other.quantity))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.customerId == null) {
            if (other.customerId != null)
                return false;
        }
        else if (!this.customerId.equals(other.customerId))
            return false;
        if (this.saleOrderId == null) {
            if (other.saleOrderId != null)
                return false;
        }
        else if (!this.saleOrderId.equals(other.saleOrderId))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.updtedAt == null) {
            if (other.updtedAt != null)
                return false;
        }
        else if (!this.updtedAt.equals(other.updtedAt))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.corpId == null) {
            if (other.corpId != null)
                return false;
        }
        else if (!this.corpId.equals(other.corpId))
            return false;
        if (this.occurAt == null) {
            if (other.occurAt != null)
                return false;
        }
        else if (!this.occurAt.equals(other.occurAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
        result = prime * result + ((this.saleOrderId == null) ? 0 : this.saleOrderId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.updtedAt == null) ? 0 : this.updtedAt.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.corpId == null) ? 0 : this.corpId.hashCode());
        result = prime * result + ((this.occurAt == null) ? 0 : this.occurAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MisSaleOrderItem (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(price);
        sb.append(", ").append(customerId);
        sb.append(", ").append(saleOrderId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updtedAt);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(corpId);
        sb.append(", ").append(occurAt);

        sb.append(")");
        return sb.toString();
    }
}
