/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MisStockPlaceItemSub implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long stockPlaceItemId;
    private BigDecimal quantity;
    private String orginCode;
    private String productCode;

    public MisStockPlaceItemSub() {}

    public MisStockPlaceItemSub(MisStockPlaceItemSub value) {
        this.id = value.id;
        this.stockPlaceItemId = value.stockPlaceItemId;
        this.quantity = value.quantity;
        this.orginCode = value.orginCode;
        this.productCode = value.productCode;
    }

    public MisStockPlaceItemSub(
        Long id,
        Long stockPlaceItemId,
        BigDecimal quantity,
        String orginCode,
        String productCode
    ) {
        this.id = id;
        this.stockPlaceItemId = stockPlaceItemId;
        this.quantity = quantity;
        this.orginCode = orginCode;
        this.productCode = productCode;
    }

    /**
     * Getter for <code>public.mis_stock_place_item_sub.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.mis_stock_place_item_sub.id</code>.
     */
    public MisStockPlaceItemSub setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for
     * <code>public.mis_stock_place_item_sub.stock_place_item_id</code>.
     */
    public Long getStockPlaceItemId() {
        return this.stockPlaceItemId;
    }

    /**
     * Setter for
     * <code>public.mis_stock_place_item_sub.stock_place_item_id</code>.
     */
    public MisStockPlaceItemSub setStockPlaceItemId(Long stockPlaceItemId) {
        this.stockPlaceItemId = stockPlaceItemId;
        return this;
    }

    /**
     * Getter for <code>public.mis_stock_place_item_sub.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>public.mis_stock_place_item_sub.quantity</code>.
     */
    public MisStockPlaceItemSub setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Getter for <code>public.mis_stock_place_item_sub.orgin_code</code>.
     */
    public String getOrginCode() {
        return this.orginCode;
    }

    /**
     * Setter for <code>public.mis_stock_place_item_sub.orgin_code</code>.
     */
    public MisStockPlaceItemSub setOrginCode(String orginCode) {
        this.orginCode = orginCode;
        return this;
    }

    /**
     * Getter for <code>public.mis_stock_place_item_sub.product_code</code>.
     */
    public String getProductCode() {
        return this.productCode;
    }

    /**
     * Setter for <code>public.mis_stock_place_item_sub.product_code</code>.
     */
    public MisStockPlaceItemSub setProductCode(String productCode) {
        this.productCode = productCode;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MisStockPlaceItemSub other = (MisStockPlaceItemSub) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.stockPlaceItemId == null) {
            if (other.stockPlaceItemId != null)
                return false;
        }
        else if (!this.stockPlaceItemId.equals(other.stockPlaceItemId))
            return false;
        if (this.quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!this.quantity.equals(other.quantity))
            return false;
        if (this.orginCode == null) {
            if (other.orginCode != null)
                return false;
        }
        else if (!this.orginCode.equals(other.orginCode))
            return false;
        if (this.productCode == null) {
            if (other.productCode != null)
                return false;
        }
        else if (!this.productCode.equals(other.productCode))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.stockPlaceItemId == null) ? 0 : this.stockPlaceItemId.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.orginCode == null) ? 0 : this.orginCode.hashCode());
        result = prime * result + ((this.productCode == null) ? 0 : this.productCode.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MisStockPlaceItemSub (");

        sb.append(id);
        sb.append(", ").append(stockPlaceItemId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(orginCode);
        sb.append(", ").append(productCode);

        sb.append(")");
        return sb.toString();
    }
}
