/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuAction implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long menuId;
    private String name;
    private String code;

    public SysMenuAction() {}

    public SysMenuAction(SysMenuAction value) {
        this.id = value.id;
        this.menuId = value.menuId;
        this.name = value.name;
        this.code = value.code;
    }

    public SysMenuAction(
        Long id,
        Long menuId,
        String name,
        String code
    ) {
        this.id = id;
        this.menuId = menuId;
        this.name = name;
        this.code = code;
    }

    /**
     * Getter for <code>public.sys_menu_action.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.sys_menu_action.id</code>.
     */
    public SysMenuAction setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.sys_menu_action.menu_id</code>.
     */
    public Long getMenuId() {
        return this.menuId;
    }

    /**
     * Setter for <code>public.sys_menu_action.menu_id</code>.
     */
    public SysMenuAction setMenuId(Long menuId) {
        this.menuId = menuId;
        return this;
    }

    /**
     * Getter for <code>public.sys_menu_action.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.sys_menu_action.name</code>.
     */
    public SysMenuAction setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.sys_menu_action.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>public.sys_menu_action.code</code>.
     */
    public SysMenuAction setCode(String code) {
        this.code = code;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SysMenuAction other = (SysMenuAction) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.menuId == null) {
            if (other.menuId != null)
                return false;
        }
        else if (!this.menuId.equals(other.menuId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.menuId == null) ? 0 : this.menuId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysMenuAction (");

        sb.append(id);
        sb.append(", ").append(menuId);
        sb.append(", ").append(name);
        sb.append(", ").append(code);

        sb.append(")");
        return sb.toString();
    }
}
