TRUNCATE "sys_menu";
INSERT INTO "sys_menu" ("id", "name", "path", "icon_url", "parent_id", "corp_id", "code") VALUES
                                                                                              (13,	'项目管理',	'/project',	'assets/icons/menu/icon_project.png',	12,	1,	NULL),
                                                                                              (20,	'库存管理',	'/store',	'assets/icons/menu/icon_store.png',	NULL,	1,	NULL),
                                                                                              (21,	'仓库',	'/store',	'assets/icons/menu/icon_store.png',	20,	1,	NULL),
                                                                                              (22,	'库存',	'/stock',	'assets/icons/menu/icon_stock.png',	20,	1,	NULL),
                                                                                              (25,	'销售管理',	'/sale',	'assets/icons/menu/icon_bill_sale.png',	23,	1,	NULL),
                                                                                              (24,	'采购管理',	'/purchase',	'assets/icons/menu/icon_bill_purchase.png',	23,	1,	NULL),
                                                                                              (23,	'业务单据',	'/purchase',	'assets/icons/menu/icon_bill_purchase.png',	NULL,	1,	NULL),
                                                                                              (26,	'财务',	'/finance',	'assets/icons/menu/icon_finanace.png',	NULL,	1,	NULL),
                                                                                              (27,	'收入',	'/income',	'assets/icons/menu/icon_bill_income.png',	26,	1,	NULL),
                                                                                              (28,	'支出',	'/expense',	'assets/icons/menu/icon_bill_expense.png',	26,	1,	NULL),
                                                                                              (29,	'审核',	'/check',	'assets/icons/menu/icon_bill_check.png',	26,	1,	NULL),
                                                                                              (1,	'产品管理',	'/product',	'assets/icons/menu/icon_product.png',	NULL,	1,	NULL),
                                                                                              (4,	'客户管理',	'/customer',	'assets/icons/menu/icon_customer.png',	3,	1,	NULL),
                                                                                              (3,	'客户管理',	'/customer',	'assets/icons/menu/icon_customer.png',	NULL,	1,	NULL),
                                                                                              (2,	'产品分类',	'/category',	'assets/icons/menu/icon_category.png',	1,	1,	NULL),
                                                                                              (14,	'系统管理',	'/manager',	'assets/icons/menu/icon_manage.png',	NULL,	1,	NULL),
                                                                                              (10,	'基地管理',	'/park',	'assets/icons/menu/icon_base.png',	NULL,	1,	NULL),
                                                                                              (12,	'项目管理',	'/project',	'assets/icons/menu/icon_project.png',	NULL,	1,	NULL),
                                                                                              (15,	'人员管理',	'/manager',	'assets/icons/menu/icon_manager.png',	14,	1,	NULL),
                                                                                              (6,	'产品管理',	'/product',	'assets/icons/menu/icon_product.png',	1,	1,	NULL),
                                                                                              (9,	'合约管理',	'/contractSearch',	'assets/icons/menu/icon_contract.png',	3,	1,	NULL),
                                                                                              (11,	'基地管理',	'/park',	'assets/icons/menu/icon_base.png',	10,	1,	NULL);