server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://127.0.0.1:5432/db_agri
    username: admin
    password: password
  data:
    mongodb:
      database: agri_db
      username: root
      password: example
      gridfs:
        database: agri_db_images
      host: localhost
      port: 27017
      authentication-database: admin

jjwt:
  secret: ReactIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
  expiration: 691200

image:
  path: /Users/mac/work/temp/upload/
  server: http://image.test.com/
