server:
  port: 9410

spring:
  webflux:
    problemdetails:
      enabled: true
  r2dbc:
    url: r2dbc:pool:postgresql://127.0.0.1:5432/db_agri
    username: admin
    password: pgsql@hbzn2023
  data:
    mongodb:
      uri: mongodb://admin:admin_hbzn2023@localhost:27017/agri_db?authSource=admin&authMechanism=SCRAM-SHA-1
      #database: agri_db
      #username: admin
      #password: admin_hbzn2023
      #host: localhost
      #port: 27017
      #authentication-database: admin

jjwt:
  secret: ReactIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
  expiration: 691200

