/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables;


import com.agri.mis.db.Keys;
import com.agri.mis.db.Public;
import com.agri.mis.db.tables.records.BatchBaseRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchBase extends TableImpl<BatchBaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.batch_base</code>
     */
    public static final BatchBase BATCH_BASE = new BatchBase();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BatchBaseRecord> getRecordType() {
        return BatchBaseRecord.class;
    }

    /**
     * The column <code>public.batch_base.id</code>.
     */
    public final TableField<BatchBaseRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.batch_base.batch_id</code>.
     */
    public final TableField<BatchBaseRecord, Long> BATCH_ID = createField(DSL.name("batch_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.batch_base.park_base_id</code>.
     */
    public final TableField<BatchBaseRecord, Long> PARK_BASE_ID = createField(DSL.name("park_base_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.batch_base.area</code>.
     */
    public final TableField<BatchBaseRecord, Double> AREA = createField(DSL.name("area"), SQLDataType.DOUBLE.nullable(false), this, "");

    private BatchBase(Name alias, Table<BatchBaseRecord> aliased) {
        this(alias, aliased, null);
    }

    private BatchBase(Name alias, Table<BatchBaseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.batch_base</code> table reference
     */
    public BatchBase(String alias) {
        this(DSL.name(alias), BATCH_BASE);
    }

    /**
     * Create an aliased <code>public.batch_base</code> table reference
     */
    public BatchBase(Name alias) {
        this(alias, BATCH_BASE);
    }

    /**
     * Create a <code>public.batch_base</code> table reference
     */
    public BatchBase() {
        this(DSL.name("batch_base"), null);
    }

    public <O extends Record> BatchBase(Table<O> child, ForeignKey<O, BatchBaseRecord> key) {
        super(child, key, BATCH_BASE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<BatchBaseRecord, Long> getIdentity() {
        return (Identity<BatchBaseRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<BatchBaseRecord> getPrimaryKey() {
        return Keys.BATCH_BASE_PKEY;
    }

    @Override
    public BatchBase as(String alias) {
        return new BatchBase(DSL.name(alias), this);
    }

    @Override
    public BatchBase as(Name alias) {
        return new BatchBase(alias, this);
    }

    @Override
    public BatchBase as(Table<?> alias) {
        return new BatchBase(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BatchBase rename(String name) {
        return new BatchBase(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BatchBase rename(Name name) {
        return new BatchBase(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BatchBase rename(Table<?> name) {
        return new BatchBase(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super Long, ? super Long, ? super Double, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super Long, ? super Long, ? super Double, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
