/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables;


import com.agri.mis.db.Keys;
import com.agri.mis.db.Public;
import com.agri.mis.db.tables.records.CmsTagRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsTag extends TableImpl<CmsTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.cms_tag</code>
     */
    public static final CmsTag CMS_TAG = new CmsTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CmsTagRecord> getRecordType() {
        return CmsTagRecord.class;
    }

    /**
     * The column <code>public.cms_tag.id</code>.
     */
    public final TableField<CmsTagRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.cms_tag.name</code>.
     */
    public final TableField<CmsTagRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private CmsTag(Name alias, Table<CmsTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private CmsTag(Name alias, Table<CmsTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.cms_tag</code> table reference
     */
    public CmsTag(String alias) {
        this(DSL.name(alias), CMS_TAG);
    }

    /**
     * Create an aliased <code>public.cms_tag</code> table reference
     */
    public CmsTag(Name alias) {
        this(alias, CMS_TAG);
    }

    /**
     * Create a <code>public.cms_tag</code> table reference
     */
    public CmsTag() {
        this(DSL.name("cms_tag"), null);
    }

    public <O extends Record> CmsTag(Table<O> child, ForeignKey<O, CmsTagRecord> key) {
        super(child, key, CMS_TAG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CmsTagRecord, Long> getIdentity() {
        return (Identity<CmsTagRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CmsTagRecord> getPrimaryKey() {
        return Keys.CMS_TAG_PKEY;
    }

    @Override
    public CmsTag as(String alias) {
        return new CmsTag(DSL.name(alias), this);
    }

    @Override
    public CmsTag as(Name alias) {
        return new CmsTag(alias, this);
    }

    @Override
    public CmsTag as(Table<?> alias) {
        return new CmsTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CmsTag rename(String name) {
        return new CmsTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CmsTag rename(Name name) {
        return new CmsTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CmsTag rename(Table<?> name) {
        return new CmsTag(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
