/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables;


import com.agri.mis.db.Keys;
import com.agri.mis.db.Public;
import com.agri.mis.db.tables.records.CorpParkRecord;

import java.time.LocalDate;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorpPark extends TableImpl<CorpParkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.corp_park</code>
     */
    public static final CorpPark CORP_PARK = new CorpPark();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CorpParkRecord> getRecordType() {
        return CorpParkRecord.class;
    }

    /**
     * The column <code>public.corp_park.id</code>.
     */
    public final TableField<CorpParkRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.corp_park.name</code>.
     */
    public final TableField<CorpParkRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.corp_park.description</code>.
     */
    public final TableField<CorpParkRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.corp_park.image_url</code>.
     */
    public final TableField<CorpParkRecord, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.corp_park.address_id</code>.
     */
    public final TableField<CorpParkRecord, Long> ADDRESS_ID = createField(DSL.name("address_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.corp_park.corp_id</code>.
     */
    public final TableField<CorpParkRecord, Long> CORP_ID = createField(DSL.name("corp_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.corp_park.area</code>.
     */
    public final TableField<CorpParkRecord, Double> AREA = createField(DSL.name("area"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.corp_park.area_use</code>.
     */
    public final TableField<CorpParkRecord, Double> AREA_USE = createField(DSL.name("area_use"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.corp_park.created_at</code>.
     */
    public final TableField<CorpParkRecord, LocalDate> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATE, this, "");

    private CorpPark(Name alias, Table<CorpParkRecord> aliased) {
        this(alias, aliased, null);
    }

    private CorpPark(Name alias, Table<CorpParkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.corp_park</code> table reference
     */
    public CorpPark(String alias) {
        this(DSL.name(alias), CORP_PARK);
    }

    /**
     * Create an aliased <code>public.corp_park</code> table reference
     */
    public CorpPark(Name alias) {
        this(alias, CORP_PARK);
    }

    /**
     * Create a <code>public.corp_park</code> table reference
     */
    public CorpPark() {
        this(DSL.name("corp_park"), null);
    }

    public <O extends Record> CorpPark(Table<O> child, ForeignKey<O, CorpParkRecord> key) {
        super(child, key, CORP_PARK);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CorpParkRecord, Long> getIdentity() {
        return (Identity<CorpParkRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CorpParkRecord> getPrimaryKey() {
        return Keys.PARK_PKEY;
    }

    @Override
    public CorpPark as(String alias) {
        return new CorpPark(DSL.name(alias), this);
    }

    @Override
    public CorpPark as(Name alias) {
        return new CorpPark(alias, this);
    }

    @Override
    public CorpPark as(Table<?> alias) {
        return new CorpPark(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CorpPark rename(String name) {
        return new CorpPark(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CorpPark rename(Name name) {
        return new CorpPark(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CorpPark rename(Table<?> name) {
        return new CorpPark(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, Long, Long, Double, Double, LocalDate> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super Long, ? super String, ? super String, ? super String, ? super Long, ? super Long, ? super Double, ? super Double, ? super LocalDate, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super Long, ? super String, ? super String, ? super String, ? super Long, ? super Long, ? super Double, ? super Double, ? super LocalDate, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
