/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables;


import com.agri.mis.db.Keys;
import com.agri.mis.db.Public;
import com.agri.mis.db.tables.records.DocResourceRecord;

import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function13;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocResource extends TableImpl<DocResourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.doc_resource</code>
     */
    public static final DocResource DOC_RESOURCE = new DocResource();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DocResourceRecord> getRecordType() {
        return DocResourceRecord.class;
    }

    /**
     * The column <code>public.doc_resource.id</code>.
     */
    public final TableField<DocResourceRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.doc_resource.name</code>.
     */
    public final TableField<DocResourceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.doc_resource.doc_type</code>.
     */
    public final TableField<DocResourceRecord, String> DOC_TYPE = createField(DSL.name("doc_type"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.doc_resource.doc_url</code>.
     */
    public final TableField<DocResourceRecord, String> DOC_URL = createField(DSL.name("doc_url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.doc_resource.show_image</code>.
     */
    public final TableField<DocResourceRecord, String> SHOW_IMAGE = createField(DSL.name("show_image"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.doc_resource.entity_id</code>.
     */
    public final TableField<DocResourceRecord, Long> ENTITY_ID = createField(DSL.name("entity_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.doc_resource.entity_name</code>.
     */
    public final TableField<DocResourceRecord, String> ENTITY_NAME = createField(DSL.name("entity_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.doc_resource.created_at</code>.
     */
    public final TableField<DocResourceRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.doc_resource.corp_id</code>.
     */
    public final TableField<DocResourceRecord, Long> CORP_ID = createField(DSL.name("corp_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.doc_resource.group_name</code>.
     */
    public final TableField<DocResourceRecord, String> GROUP_NAME = createField(DSL.name("group_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.doc_resource.created_user_id</code>.
     */
    public final TableField<DocResourceRecord, Long> CREATED_USER_ID = createField(DSL.name("created_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.doc_resource.doc_ext</code>.
     */
    public final TableField<DocResourceRecord, String> DOC_EXT = createField(DSL.name("doc_ext"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.doc_resource.created_by</code>.
     */
    public final TableField<DocResourceRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    private DocResource(Name alias, Table<DocResourceRecord> aliased) {
        this(alias, aliased, null);
    }

    private DocResource(Name alias, Table<DocResourceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.doc_resource</code> table reference
     */
    public DocResource(String alias) {
        this(DSL.name(alias), DOC_RESOURCE);
    }

    /**
     * Create an aliased <code>public.doc_resource</code> table reference
     */
    public DocResource(Name alias) {
        this(alias, DOC_RESOURCE);
    }

    /**
     * Create a <code>public.doc_resource</code> table reference
     */
    public DocResource() {
        this(DSL.name("doc_resource"), null);
    }

    public <O extends Record> DocResource(Table<O> child, ForeignKey<O, DocResourceRecord> key) {
        super(child, key, DOC_RESOURCE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DocResourceRecord, Long> getIdentity() {
        return (Identity<DocResourceRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DocResourceRecord> getPrimaryKey() {
        return Keys.DOC_RESOURCE_PKEY;
    }

    @Override
    public DocResource as(String alias) {
        return new DocResource(DSL.name(alias), this);
    }

    @Override
    public DocResource as(Name alias) {
        return new DocResource(alias, this);
    }

    @Override
    public DocResource as(Table<?> alias) {
        return new DocResource(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DocResource rename(String name) {
        return new DocResource(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DocResource rename(Name name) {
        return new DocResource(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DocResource rename(Table<?> name) {
        return new DocResource(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, String, String, Long, String, LocalDateTime, Long, String, Long, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function13<? super Long, ? super String, ? super String, ? super String, ? super String, ? super Long, ? super String, ? super LocalDateTime, ? super Long, ? super String, ? super Long, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function13<? super Long, ? super String, ? super String, ? super String, ? super String, ? super Long, ? super String, ? super LocalDateTime, ? super Long, ? super String, ? super Long, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
