/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables;


import com.agri.mis.db.Keys;
import com.agri.mis.db.Public;
import com.agri.mis.db.tables.records.MarkProductRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarkProduct extends TableImpl<MarkProductRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mark_product</code>
     */
    public static final MarkProduct MARK_PRODUCT = new MarkProduct();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MarkProductRecord> getRecordType() {
        return MarkProductRecord.class;
    }

    /**
     * The column <code>public.mark_product.id</code>.
     */
    public final TableField<MarkProductRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.mark_product.name</code>.
     */
    public final TableField<MarkProductRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.mark_product.code</code>.
     */
    public final TableField<MarkProductRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.mark_product.category_id</code>.
     */
    public final TableField<MarkProductRecord, Long> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mark_product.image_url</code>.
     */
    public final TableField<MarkProductRecord, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mark_product.calc_unit</code>.
     */
    public final TableField<MarkProductRecord, String> CALC_UNIT = createField(DSL.name("calc_unit"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.mark_product.description</code>.
     */
    public final TableField<MarkProductRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    private MarkProduct(Name alias, Table<MarkProductRecord> aliased) {
        this(alias, aliased, null);
    }

    private MarkProduct(Name alias, Table<MarkProductRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.mark_product</code> table reference
     */
    public MarkProduct(String alias) {
        this(DSL.name(alias), MARK_PRODUCT);
    }

    /**
     * Create an aliased <code>public.mark_product</code> table reference
     */
    public MarkProduct(Name alias) {
        this(alias, MARK_PRODUCT);
    }

    /**
     * Create a <code>public.mark_product</code> table reference
     */
    public MarkProduct() {
        this(DSL.name("mark_product"), null);
    }

    public <O extends Record> MarkProduct(Table<O> child, ForeignKey<O, MarkProductRecord> key) {
        super(child, key, MARK_PRODUCT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<MarkProductRecord, Long> getIdentity() {
        return (Identity<MarkProductRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<MarkProductRecord> getPrimaryKey() {
        return Keys.MK_PRODUCT_PKEY;
    }

    @Override
    public MarkProduct as(String alias) {
        return new MarkProduct(DSL.name(alias), this);
    }

    @Override
    public MarkProduct as(Name alias) {
        return new MarkProduct(alias, this);
    }

    @Override
    public MarkProduct as(Table<?> alias) {
        return new MarkProduct(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MarkProduct rename(String name) {
        return new MarkProduct(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MarkProduct rename(Name name) {
        return new MarkProduct(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MarkProduct rename(Table<?> name) {
        return new MarkProduct(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, Long, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super String, ? super String, ? super Long, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super String, ? super String, ? super Long, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
