/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables;


import com.agri.mis.db.Keys;
import com.agri.mis.db.Public;
import com.agri.mis.db.tables.records.MarkProductRiskRecord;

import java.math.BigDecimal;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarkProductRisk extends TableImpl<MarkProductRiskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mark_product_risk</code>
     */
    public static final MarkProductRisk MARK_PRODUCT_RISK = new MarkProductRisk();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MarkProductRiskRecord> getRecordType() {
        return MarkProductRiskRecord.class;
    }

    /**
     * The column <code>public.mark_product_risk.cycle_name</code>.
     */
    public final TableField<MarkProductRiskRecord, String> CYCLE_NAME = createField(DSL.name("cycle_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.mark_product_risk.risk_category</code>.
     */
    public final TableField<MarkProductRiskRecord, String> RISK_CATEGORY = createField(DSL.name("risk_category"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.mark_product_risk.description</code>.
     */
    public final TableField<MarkProductRiskRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>public.mark_product_risk.solution</code>.
     */
    public final TableField<MarkProductRiskRecord, String> SOLUTION = createField(DSL.name("solution"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>public.mark_product_risk.fee_amount</code>.
     */
    public final TableField<MarkProductRiskRecord, BigDecimal> FEE_AMOUNT = createField(DSL.name("fee_amount"), SQLDataType.NUMERIC(12, 2), this, "");

    /**
     * The column <code>public.mark_product_risk.name</code>.
     */
    public final TableField<MarkProductRiskRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.mark_product_risk.id</code>.
     */
    public final TableField<MarkProductRiskRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.mark_product_risk.product_batch_id</code>.
     */
    public final TableField<MarkProductRiskRecord, Long> PRODUCT_BATCH_ID = createField(DSL.name("product_batch_id"), SQLDataType.BIGINT, this, "");

    private MarkProductRisk(Name alias, Table<MarkProductRiskRecord> aliased) {
        this(alias, aliased, null);
    }

    private MarkProductRisk(Name alias, Table<MarkProductRiskRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.mark_product_risk</code> table reference
     */
    public MarkProductRisk(String alias) {
        this(DSL.name(alias), MARK_PRODUCT_RISK);
    }

    /**
     * Create an aliased <code>public.mark_product_risk</code> table reference
     */
    public MarkProductRisk(Name alias) {
        this(alias, MARK_PRODUCT_RISK);
    }

    /**
     * Create a <code>public.mark_product_risk</code> table reference
     */
    public MarkProductRisk() {
        this(DSL.name("mark_product_risk"), null);
    }

    public <O extends Record> MarkProductRisk(Table<O> child, ForeignKey<O, MarkProductRiskRecord> key) {
        super(child, key, MARK_PRODUCT_RISK);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<MarkProductRiskRecord, Long> getIdentity() {
        return (Identity<MarkProductRiskRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<MarkProductRiskRecord> getPrimaryKey() {
        return Keys.PRODUCT_RISK_PKEY;
    }

    @Override
    public MarkProductRisk as(String alias) {
        return new MarkProductRisk(DSL.name(alias), this);
    }

    @Override
    public MarkProductRisk as(Name alias) {
        return new MarkProductRisk(alias, this);
    }

    @Override
    public MarkProductRisk as(Table<?> alias) {
        return new MarkProductRisk(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MarkProductRisk rename(String name) {
        return new MarkProductRisk(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MarkProductRisk rename(Name name) {
        return new MarkProductRisk(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MarkProductRisk rename(Table<?> name) {
        return new MarkProductRisk(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, String, String, BigDecimal, String, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super String, ? super String, ? super String, ? super String, ? super BigDecimal, ? super String, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super String, ? super String, ? super String, ? super String, ? super BigDecimal, ? super String, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
