/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables;


import com.agri.mis.db.Keys;
import com.agri.mis.db.Public;
import com.agri.mis.db.tables.records.MisProductionOrderRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function15;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row15;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MisProductionOrder extends TableImpl<MisProductionOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mis_production_order</code>
     */
    public static final MisProductionOrder MIS_PRODUCTION_ORDER = new MisProductionOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MisProductionOrderRecord> getRecordType() {
        return MisProductionOrderRecord.class;
    }

    /**
     * The column <code>public.mis_production_order.id</code>.
     */
    public final TableField<MisProductionOrderRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.mis_production_order.name</code>.
     */
    public final TableField<MisProductionOrderRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.mis_production_order.order_no</code>.
     */
    public final TableField<MisProductionOrderRecord, String> ORDER_NO = createField(DSL.name("order_no"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.mis_production_order.quantity</code>.
     */
    public final TableField<MisProductionOrderRecord, BigDecimal> QUANTITY = createField(DSL.name("quantity"), SQLDataType.NUMERIC(12, 3), this, "");

    /**
     * The column <code>public.mis_production_order.amount</code>.
     */
    public final TableField<MisProductionOrderRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC(12, 3), this, "");

    /**
     * The column <code>public.mis_production_order.batch_id</code>.
     */
    public final TableField<MisProductionOrderRecord, Long> BATCH_ID = createField(DSL.name("batch_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mis_production_order.batch_name</code>.
     */
    public final TableField<MisProductionOrderRecord, String> BATCH_NAME = createField(DSL.name("batch_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.mis_production_order.created_at</code>.
     */
    public final TableField<MisProductionOrderRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.mis_production_order.created_by</code>.
     */
    public final TableField<MisProductionOrderRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.mis_production_order.updted_at</code>.
     */
    public final TableField<MisProductionOrderRecord, LocalDateTime> UPDTED_AT = createField(DSL.name("updted_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.mis_production_order.updated_by</code>.
     */
    public final TableField<MisProductionOrderRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.mis_production_order.corp_id</code>.
     */
    public final TableField<MisProductionOrderRecord, Long> CORP_ID = createField(DSL.name("corp_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mis_production_order.status</code>.
     */
    public final TableField<MisProductionOrderRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.mis_production_order.occur_at</code>.
     */
    public final TableField<MisProductionOrderRecord, LocalDateTime> OCCUR_AT = createField(DSL.name("occur_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.mis_production_order.created_user_id</code>.
     */
    public final TableField<MisProductionOrderRecord, Long> CREATED_USER_ID = createField(DSL.name("created_user_id"), SQLDataType.BIGINT, this, "");

    private MisProductionOrder(Name alias, Table<MisProductionOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private MisProductionOrder(Name alias, Table<MisProductionOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.mis_production_order</code> table
     * reference
     */
    public MisProductionOrder(String alias) {
        this(DSL.name(alias), MIS_PRODUCTION_ORDER);
    }

    /**
     * Create an aliased <code>public.mis_production_order</code> table
     * reference
     */
    public MisProductionOrder(Name alias) {
        this(alias, MIS_PRODUCTION_ORDER);
    }

    /**
     * Create a <code>public.mis_production_order</code> table reference
     */
    public MisProductionOrder() {
        this(DSL.name("mis_production_order"), null);
    }

    public <O extends Record> MisProductionOrder(Table<O> child, ForeignKey<O, MisProductionOrderRecord> key) {
        super(child, key, MIS_PRODUCTION_ORDER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<MisProductionOrderRecord, Long> getIdentity() {
        return (Identity<MisProductionOrderRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<MisProductionOrderRecord> getPrimaryKey() {
        return Keys.PRODUCTION_ORDER_PKEY;
    }

    @Override
    public MisProductionOrder as(String alias) {
        return new MisProductionOrder(DSL.name(alias), this);
    }

    @Override
    public MisProductionOrder as(Name alias) {
        return new MisProductionOrder(alias, this);
    }

    @Override
    public MisProductionOrder as(Table<?> alias) {
        return new MisProductionOrder(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MisProductionOrder rename(String name) {
        return new MisProductionOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MisProductionOrder rename(Name name) {
        return new MisProductionOrder(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MisProductionOrder rename(Table<?> name) {
        return new MisProductionOrder(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, String, String, BigDecimal, BigDecimal, Long, String, LocalDateTime, String, LocalDateTime, String, Long, Integer, LocalDateTime, Long> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function15<? super Long, ? super String, ? super String, ? super BigDecimal, ? super BigDecimal, ? super Long, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? super Long, ? super Integer, ? super LocalDateTime, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function15<? super Long, ? super String, ? super String, ? super BigDecimal, ? super BigDecimal, ? super Long, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? super Long, ? super Integer, ? super LocalDateTime, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
