/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables;


import com.agri.mis.db.Keys;
import com.agri.mis.db.Public;
import com.agri.mis.db.tables.records.MisStockItemRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function13;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MisStockItem extends TableImpl<MisStockItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mis_stock_item</code>
     */
    public static final MisStockItem MIS_STOCK_ITEM = new MisStockItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MisStockItemRecord> getRecordType() {
        return MisStockItemRecord.class;
    }

    /**
     * The column <code>public.mis_stock_item.id</code>.
     */
    public final TableField<MisStockItemRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.mis_stock_item.product_id</code>.
     */
    public final TableField<MisStockItemRecord, Long> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mis_stock_item.quantity</code>.
     */
    public final TableField<MisStockItemRecord, BigDecimal> QUANTITY = createField(DSL.name("quantity"), SQLDataType.NUMERIC(12, 3), this, "");

    /**
     * The column <code>public.mis_stock_item.price</code>.
     */
    public final TableField<MisStockItemRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.NUMERIC(12, 3), this, "");

    /**
     * The column <code>public.mis_stock_item.direction</code>.
     */
    public final TableField<MisStockItemRecord, Integer> DIRECTION = createField(DSL.name("direction"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.mis_stock_item.store_id</code>.
     */
    public final TableField<MisStockItemRecord, Long> STORE_ID = createField(DSL.name("store_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mis_stock_item.stock_id</code>.
     */
    public final TableField<MisStockItemRecord, Long> STOCK_ID = createField(DSL.name("stock_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mis_stock_item.occur_at</code>.
     */
    public final TableField<MisStockItemRecord, LocalDate> OCCUR_AT = createField(DSL.name("occur_at"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.mis_stock_item.created_at</code>.
     */
    public final TableField<MisStockItemRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.mis_stock_item.created_by</code>.
     */
    public final TableField<MisStockItemRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.mis_stock_item.updted_at</code>.
     */
    public final TableField<MisStockItemRecord, LocalDateTime> UPDTED_AT = createField(DSL.name("updted_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.mis_stock_item.updated_by</code>.
     */
    public final TableField<MisStockItemRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.mis_stock_item.corp_id</code>.
     */
    public final TableField<MisStockItemRecord, Long> CORP_ID = createField(DSL.name("corp_id"), SQLDataType.BIGINT, this, "");

    private MisStockItem(Name alias, Table<MisStockItemRecord> aliased) {
        this(alias, aliased, null);
    }

    private MisStockItem(Name alias, Table<MisStockItemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.mis_stock_item</code> table reference
     */
    public MisStockItem(String alias) {
        this(DSL.name(alias), MIS_STOCK_ITEM);
    }

    /**
     * Create an aliased <code>public.mis_stock_item</code> table reference
     */
    public MisStockItem(Name alias) {
        this(alias, MIS_STOCK_ITEM);
    }

    /**
     * Create a <code>public.mis_stock_item</code> table reference
     */
    public MisStockItem() {
        this(DSL.name("mis_stock_item"), null);
    }

    public <O extends Record> MisStockItem(Table<O> child, ForeignKey<O, MisStockItemRecord> key) {
        super(child, key, MIS_STOCK_ITEM);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<MisStockItemRecord, Long> getIdentity() {
        return (Identity<MisStockItemRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<MisStockItemRecord> getPrimaryKey() {
        return Keys.STOCK_ITEM_PKEY;
    }

    @Override
    public MisStockItem as(String alias) {
        return new MisStockItem(DSL.name(alias), this);
    }

    @Override
    public MisStockItem as(Name alias) {
        return new MisStockItem(alias, this);
    }

    @Override
    public MisStockItem as(Table<?> alias) {
        return new MisStockItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MisStockItem rename(String name) {
        return new MisStockItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MisStockItem rename(Name name) {
        return new MisStockItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MisStockItem rename(Table<?> name) {
        return new MisStockItem(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, Long, BigDecimal, BigDecimal, Integer, Long, Long, LocalDate, LocalDateTime, String, LocalDateTime, String, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function13<? super Long, ? super Long, ? super BigDecimal, ? super BigDecimal, ? super Integer, ? super Long, ? super Long, ? super LocalDate, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function13<? super Long, ? super Long, ? super BigDecimal, ? super BigDecimal, ? super Integer, ? super Long, ? super Long, ? super LocalDate, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
