/*
 * This file is generated by jOOQ.
 */
package com.agri.mis.db.tables;


import com.agri.mis.db.Keys;
import com.agri.mis.db.Public;
import com.agri.mis.db.tables.records.MisSaleOrderItemRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function12;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MisSaleOrderItem extends TableImpl<MisSaleOrderItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mis_sale_order_item</code>
     */
    public static final MisSaleOrderItem MIS_SALE_ORDER_ITEM = new MisSaleOrderItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MisSaleOrderItemRecord> getRecordType() {
        return MisSaleOrderItemRecord.class;
    }

    /**
     * The column <code>public.mis_sale_order_item.id</code>.
     */
    public final TableField<MisSaleOrderItemRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.mis_sale_order_item.product_id</code>.
     */
    public final TableField<MisSaleOrderItemRecord, Long> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mis_sale_order_item.quantity</code>.
     */
    public final TableField<MisSaleOrderItemRecord, BigDecimal> QUANTITY = createField(DSL.name("quantity"), SQLDataType.NUMERIC(12, 3), this, "");

    /**
     * The column <code>public.mis_sale_order_item.price</code>.
     */
    public final TableField<MisSaleOrderItemRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.NUMERIC(12, 3), this, "");

    /**
     * The column <code>public.mis_sale_order_item.customer_id</code>.
     */
    public final TableField<MisSaleOrderItemRecord, Long> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mis_sale_order_item.sale_order_id</code>.
     */
    public final TableField<MisSaleOrderItemRecord, Long> SALE_ORDER_ID = createField(DSL.name("sale_order_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mis_sale_order_item.created_at</code>.
     */
    public final TableField<MisSaleOrderItemRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.mis_sale_order_item.created_by</code>.
     */
    public final TableField<MisSaleOrderItemRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.mis_sale_order_item.updted_at</code>.
     */
    public final TableField<MisSaleOrderItemRecord, LocalDateTime> UPDTED_AT = createField(DSL.name("updted_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.mis_sale_order_item.updated_by</code>.
     */
    public final TableField<MisSaleOrderItemRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.mis_sale_order_item.corp_id</code>.
     */
    public final TableField<MisSaleOrderItemRecord, Long> CORP_ID = createField(DSL.name("corp_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mis_sale_order_item.occur_at</code>.
     */
    public final TableField<MisSaleOrderItemRecord, LocalDateTime> OCCUR_AT = createField(DSL.name("occur_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private MisSaleOrderItem(Name alias, Table<MisSaleOrderItemRecord> aliased) {
        this(alias, aliased, null);
    }

    private MisSaleOrderItem(Name alias, Table<MisSaleOrderItemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.mis_sale_order_item</code> table reference
     */
    public MisSaleOrderItem(String alias) {
        this(DSL.name(alias), MIS_SALE_ORDER_ITEM);
    }

    /**
     * Create an aliased <code>public.mis_sale_order_item</code> table reference
     */
    public MisSaleOrderItem(Name alias) {
        this(alias, MIS_SALE_ORDER_ITEM);
    }

    /**
     * Create a <code>public.mis_sale_order_item</code> table reference
     */
    public MisSaleOrderItem() {
        this(DSL.name("mis_sale_order_item"), null);
    }

    public <O extends Record> MisSaleOrderItem(Table<O> child, ForeignKey<O, MisSaleOrderItemRecord> key) {
        super(child, key, MIS_SALE_ORDER_ITEM);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<MisSaleOrderItemRecord, Long> getIdentity() {
        return (Identity<MisSaleOrderItemRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<MisSaleOrderItemRecord> getPrimaryKey() {
        return Keys.SALE_ORDER_ITEM_PKEY;
    }

    @Override
    public MisSaleOrderItem as(String alias) {
        return new MisSaleOrderItem(DSL.name(alias), this);
    }

    @Override
    public MisSaleOrderItem as(Name alias) {
        return new MisSaleOrderItem(alias, this);
    }

    @Override
    public MisSaleOrderItem as(Table<?> alias) {
        return new MisSaleOrderItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MisSaleOrderItem rename(String name) {
        return new MisSaleOrderItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MisSaleOrderItem rename(Name name) {
        return new MisSaleOrderItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MisSaleOrderItem rename(Table<?> name) {
        return new MisSaleOrderItem(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, BigDecimal, BigDecimal, Long, Long, LocalDateTime, String, LocalDateTime, String, Long, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function12<? super Long, ? super Long, ? super BigDecimal, ? super BigDecimal, ? super Long, ? super Long, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? super Long, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function12<? super Long, ? super Long, ? super BigDecimal, ? super BigDecimal, ? super Long, ? super Long, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? super Long, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
